import * as vscode from 'vscode';
import { SessionSummary, DaySummary, ActivityRecord, EfficiencyStats } from './types';

export class UsageDashboardPanel implements vscode.Disposable {
  static currentPanel: UsageDashboardPanel | undefined;

  private readonly panel: vscode.WebviewPanel;
  private disposables: vscode.Disposable[] = [];
  
  private lastActivity: ActivityRecord[] = [];
  private lastProject?: string;
  private lastEfficiency?: EfficiencyStats;

  static show(): UsageDashboardPanel {
    if (UsageDashboardPanel.currentPanel) {
      UsageDashboardPanel.currentPanel.panel.reveal();
      return UsageDashboardPanel.currentPanel;
    }
    const panel = vscode.window.createWebviewPanel(
      'claudeUsageDashboard',
      'Claude Usage',
      vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    UsageDashboardPanel.currentPanel = new UsageDashboardPanel(panel);
    return UsageDashboardPanel.currentPanel;
  }

  private constructor(panel: vscode.WebviewPanel) {
    this.panel = panel;
    this.panel.onDidDispose(() => this.dispose(), null, this.disposables);
    this.panel.webview.onDidReceiveMessage(message => {
      if (message.command === 'installHooks') {
        vscode.commands.executeCommand('claudeUsage.installHooks');
      } else if (message.command === 'refresh') {
        vscode.commands.executeCommand('claudeUsage.refresh');
      } else if (message.command === 'exportSession') {
        this.exportSessionToMarkdown();
      }
    }, undefined, this.disposables);
    this.panel.webview.html = this.skeleton();
  }

  update(
    sessions: SessionSummary[], days: DaySummary[], activity: ActivityRecord[],
    hooksActive: boolean, currentProject?: string,
    liveMetrics?: { contextPct: number | null; fiveHourPct: number | null; sevenDayPct: number | null; fiveHourResetsAt: Date | null },
    efficiency?: EfficiencyStats
  ): void {
    this.lastActivity = activity;
    this.lastProject = currentProject;
    this.lastEfficiency = efficiency;
    this.panel.webview.postMessage({ type: 'update', sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency });
  }

  private async exportSessionToMarkdown(): Promise<void> {
    if (this.lastActivity.length === 0) {
      vscode.window.showWarningMessage('No activity data to export.');
      return;
    }

    let md = `# Claude Session Export: ${this.lastProject || 'Untracked Project'}\n`;
    md += `*Generated by Claude Usage Monitor*\n\n`;
    
    if (this.lastEfficiency) {
      md += `## Efficiency Stats\n`;
      md += `- **Total Tool Calls:** ${this.lastEfficiency.totalToolCalls}\n`;
      md += `- **Bash Error Rate:** ${Math.round(this.lastEfficiency.bashErrorRate * 100)}%\n`;
      if (this.lastEfficiency.sessionCostUsd) {
        md += `- **Estimated Cost (Today):** $${this.lastEfficiency.sessionCostUsd.toFixed(2)}\n`;
      }
      md += `\n`;
    }

    md += `## Tool Usage Sequence\n\n`;
    md += `| Timestamp | Event | Tool | Summary | Duration |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    // Process records - group Pre/Post if possible or just list them
    for (const r of this.lastActivity) {
      const time = new Date(r.ts).toLocaleTimeString();
      const dur = r.durationMs ? `${(r.durationMs / 1000).toFixed(1)}s` : '-';
      const event = r.event === 'PreToolUse' ? '▶ Start' : r.event === 'PostToolUse' ? '✓ End' : r.event;
      md += `| ${time} | ${event} | \`${r.tool || '-'}\` | ${r.summary || '-'} | ${dur} |\n`;
    }

    md += `\n\n--- \n*Use this log to reconcile your Anthropic billing or to document AI-driven architectural changes.*`;

    const doc = await vscode.workspace.openTextDocument({
      content: md,
      language: 'markdown'
    });
    await vscode.window.showTextDocument(doc);
  }

  reveal(): void {
    this.panel.reveal();
  }

  dispose(): void {
    UsageDashboardPanel.currentPanel = undefined;
    this.panel.dispose();
    this.disposables.forEach(d => d.dispose());
  }

  private skeleton(): string {
    return /* html */`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Claude Usage</title>
<style>
  :root {
    --bg: var(--vscode-editor-background);
    --fg: var(--vscode-editor-foreground);
    --border: var(--vscode-panel-border, #333);
    --card-bg: var(--vscode-sideBar-background, #1e1e1e);
    --accent: var(--vscode-focusBorder, #007acc);
    --accent-hover: var(--vscode-textLink-activeForeground, #005a9e);
    --muted: var(--vscode-descriptionForeground, #888);
    --green: #4ec9b0;
    --yellow: #dcdcaa;
    --red: #f44747;
    --glass-bg: rgba(255, 255, 255, 0.02);
    --glass-border: rgba(255, 255, 255, 0.06);
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', var(--vscode-font-family); font-size: 13px; color: var(--fg); background: var(--bg); padding: 24px; max-width: 1400px; margin: 0 auto; }
  
  h2 { font-size: 22px; font-weight: 700; margin-bottom: 8px; display: flex; align-items: center; gap: 10px; background: -webkit-linear-gradient(45deg, var(--accent), var(--green)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
  h3 { font-size: 13px; font-weight: 600; color: var(--fg); text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }
  h3::before { content: ''; width: 4px; height: 16px; background: var(--accent); border-radius: 2px; }

  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 1px solid var(--border); }
  button { background: var(--accent); color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-size: 13px; font-weight: 600; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.2); display: flex; align-items: center; gap: 6px; }
  button:hover { background: var(--accent-hover); transform: translateY(-1px); box-shadow: 0 4px 10px rgba(0,0,0,0.3); }

  .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 20px; margin-bottom: 32px; }
  .card { background: linear-gradient(160deg, var(--card-bg), var(--bg)); border: 1px solid var(--glass-border); border-radius: 10px; padding: 20px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s; position: relative; overflow: hidden; }
  .card::before { content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 3px; background: linear-gradient(90deg, transparent, var(--accent), transparent); transform: translateX(-100%); transition: transform 0.4s ease; }
  .card:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2); border-color: var(--border); }
  .card:hover::before { transform: translateX(0); }
  .card-label { font-size: 12px; color: var(--muted); margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600; }
  .card-value { font-size: 32px; font-weight: 700; color: var(--fg); text-shadow: 0 2px 4px rgba(0,0,0,0.2); line-height: 1; margin-bottom: 8px; }
  .card-sub { font-size: 12px; color: var(--muted); }

  .section { margin-bottom: 32px; padding: 24px; background: var(--glass-bg); border-radius: 12px; border: 1px solid var(--glass-border); }
  
  table { width: 100%; border-collapse: separate; border-spacing: 0; font-size: 13px; }
  th { text-align: left; padding: 12px 14px; color: var(--muted); font-weight: 600; border-bottom: 2px solid var(--glass-border); white-space: nowrap; }
  td { padding: 12px 14px; border-bottom: 1px solid var(--glass-border); vertical-align: middle; transition: background 0.2s; }
  tr { transition: transform 0.1s; }
  tr:hover td { background: rgba(255,255,255,0.03); }
  .model-tag { font-size: 11px; padding: 4px 10px; border-radius: 12px; background: rgba(0, 122, 204, 0.15); border: 1px solid rgba(0, 122, 204, 0.3); color: var(--accent); font-weight: 600; }
  .cost { color: var(--yellow); font-family: monospace; font-size: 14px; font-weight: bold; background: rgba(220, 220, 170, 0.1); padding: 2px 8px; border-radius: 4px; }

  .grade-badge { width: 44px; height: 44px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 22px; font-weight: 900; color: #fff; box-shadow: 0 4px 10px rgba(0,0,0,0.3); border: 2px solid rgba(255,255,255,0.2); text-shadow: 0 2px 4px rgba(0,0,0,0.3); }
  .grade-s { background: linear-gradient(135deg, #ffd700, #ff8c00); }
  .grade-a { background: linear-gradient(135deg, #4ec9b0, #007acc); }
  .grade-b { background: linear-gradient(135deg, #007acc, #c586c0); }
  .grade-c { background: linear-gradient(135deg, #888, #555); }
  .grade-f { background: linear-gradient(135deg, #f44747, #b22222); }
  
  .score-label { display: flex; flex-direction: column; align-items: flex-end; gap: 2px; }
  .score-title { font-size: 10px; color: var(--muted); text-transform: uppercase; font-weight: 700; letter-spacing: 1px; }
  .score-val { font-size: 18px; font-weight: 800; color: var(--fg); }

  .activity { max-height: 360px; overflow-y: auto; padding-right: 8px; }
  .activity::-webkit-scrollbar { width: 6px; }
  .activity::-webkit-scrollbar-track { background: transparent; }
  .activity::-webkit-scrollbar-thumb { background: var(--border); border-radius: 4px; }
  .activity-item { display: flex; gap: 16px; padding: 12px 16px; border-bottom: 1px solid var(--glass-border); font-size: 13px; align-items: center; transition: all 0.2s; border-left: 3px solid transparent; background: rgba(0,0,0,0.1); margin-bottom: 4px; border-radius: 0 6px 6px 0; }
  .activity-item:hover { background: rgba(255,255,255,0.03); border-left-color: var(--accent); transform: translateX(2px); }
  .activity-item:last-child { border-bottom: none; }
  .activity-ts { color: var(--muted); white-space: nowrap; flex-shrink: 0; font-family: monospace; font-size: 11px; }
  .activity-tool { color: var(--green); font-weight: 600; flex-shrink: 0; min-width: 90px; padding: 3px 8px; background: rgba(78, 201, 176, 0.1); border-radius: 6px; display: inline-flex; justify-content: center; }
  .activity-summary { color: var(--fg); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; }
  .activity-dur { color: var(--accent); flex-shrink: 0; font-weight: 600; background: rgba(0, 122, 204, 0.1); padding: 3px 8px; border-radius: 6px; font-size: 11px;}

  .notice { background: rgba(244, 71, 71, 0.1); border-left: 4px solid var(--red); border-radius: 4px; padding: 16px 20px; font-size: 13px; color: var(--fg); line-height: 1.5; display: flex; align-items: center; justify-content: space-between; }
  .notice code { color: var(--red); font-family: monospace; background: rgba(0,0,0,0.2); padding: 4px 8px; border-radius: 4px; display: block; margin-top: 10px; }
  .btn-install { background: var(--green); color: #000; border: none; padding: 8px 16px; border-radius: 6px; font-weight: bold; cursor: pointer; transition: opacity 0.2s; white-space: nowrap; margin-left: 20px; }
  .btn-install:hover { opacity: 0.8; }

  .empty { color: var(--muted); font-size: 14px; padding: 40px; text-align: center; font-style: italic; background: rgba(0,0,0,0.1); border-radius: 8px; }

  /* Efficiency section */
  .eff-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
  .eff-panel { background: var(--bg); border: 1px solid var(--glass-border); border-radius: 12px; padding: 20px; box-shadow: inset 0 2px 4px rgba(0,0,0,0.05); }
  .eff-panel h4 { font-size: 12px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: 1px; margin-bottom: 20px; border-bottom: 1px solid var(--glass-border); padding-bottom: 10px; }
  
  .tool-bar-row { display: flex; align-items: center; gap: 14px; margin-bottom: 12px; font-size: 13px; }
  .tool-bar-label { width: 100px; flex-shrink: 0; color: var(--fg); font-weight: 600; }
  .tool-bar-track { flex: 1; height: 12px; background: rgba(0,0,0,0.2); border-radius: 6px; overflow: hidden; box-shadow: inset 0 1px 3px rgba(0,0,0,0.3); }
  .tool-bar-fill { height: 100%; border-radius: 6px; transition: width 0.6s cubic-bezier(0.1, 0.8, 0.2, 1); background-image: linear-gradient(45deg, rgba(255,255,255,.15) 25%, transparent 25%, transparent 50%, rgba(255,255,255,.15) 50%, rgba(255,255,255,.15) 75%, transparent 75%, transparent); background-size: 1rem 1rem; animation: stripemove 2s linear infinite; }
  @keyframes stripemove { 0% { background-position: 1rem 0; } 100% { background-position: 0 0; } }
  .tool-bar-count { width: 35px; text-align: right; color: var(--fg); font-weight: bold; }
  .tool-bar-dur { width: 55px; text-align: right; color: var(--muted); font-size: 11px; }
  
  .stat-row { display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px dashed var(--glass-border); font-size: 13px; }
  .stat-row:last-child { border-bottom: none; }
  .stat-val { font-weight: 700; font-size: 15px; padding: 4px 10px; border-radius: 6px; background: rgba(0,0,0,0.1); }
  .stat-val.good { color: var(--green); background: rgba(78, 201, 176, 0.15); border: 1px solid rgba(78, 201, 176, 0.2); }
  .stat-val.warn { color: var(--yellow); background: rgba(220, 220, 170, 0.15); border: 1px solid rgba(220, 220, 170, 0.2); }
  .stat-val.bad  { color: var(--red); background: rgba(244, 71, 71, 0.15); border: 1px solid rgba(244, 71, 71, 0.2); }

  .filter-bar { display: flex; align-items: center; gap: 12px; margin-bottom: 20px; }
  .filter-bar select { background: var(--bg); color: var(--fg); border: 1px solid var(--border); border-radius: 6px; padding: 8px 14px; font-size: 13px; cursor: pointer; transition: border-color 0.2s, box-shadow 0.2s; outline: none; }
  .filter-bar select:focus { border-color: var(--accent); box-shadow: 0 0 0 2px rgba(0,122,204,0.2); }
  .active-project-badge { font-size: 11px; padding: 4px 10px; border-radius: 12px; background: linear-gradient(45deg, var(--accent), var(--green)); color: #fff; font-weight: 600; box-shadow: 0 2px 6px rgba(0,122,204,0.3); }

  /* Animations */
  @keyframes fadeUp { from { opacity: 0; transform: translateY(15px); } to { opacity: 1; transform: translateY(0); } }
  .cards, .section { animation: fadeUp 0.5s cubic-bezier(0.1, 0.8, 0.2, 1) forwards; opacity: 0; }
  .cards { animation-delay: 0.1s; }
  .section:nth-of-type(1) { animation-delay: 0.2s; }
  .section:nth-of-type(2) { animation-delay: 0.3s; }
  .section:nth-of-type(3) { animation-delay: 0.4s; }
  .section:nth-of-type(4) { animation-delay: 0.5s; }
</style>
</head>
<body>
<div class="header">
  <div style="display:flex; align-items:center; gap:20px">
    <h2>⚡ Claude Usage Monitor</h2>
    <div id="score-container" style="display:flex; align-items:center; gap:12px; border-left:1px solid var(--border); padding-left:20px"></div>
  </div>
  <div style="display:flex;gap:10px">
    <button onclick="exportSession()" style="background:var(--card-bg);color:var(--fg);border:1px solid var(--glass-border)">📤 Export Session</button>
    <button onclick="refresh()">↻ Refresh</button>
  </div>
</div>

<div id="cards" class="cards"></div>

<div class="section">
  <h3>Activity Feed</h3>
  <div id="activity-feed" class="activity"><p class="empty">Waiting for activity…</p></div>
  <div id="hooks-notice" style="display:none;margin-top:8px"></div>
</div>

<div class="section">
  <h3>Efficiency</h3>
  <div id="efficiency-section" class="eff-grid"></div>
</div>

<div class="section">
  <div class="filter-bar">
    <h3 style="margin:0">Sessions</h3>
    <select id="project-filter" onchange="applyFilter()">
      <option value="">All projects</option>
    </select>
    <span id="active-badge" style="display:none" class="active-project-badge"></span>
  </div>
  <div id="sessions-table"></div>
</div>

<div class="section">
  <h3>Daily Usage</h3>
  <div id="days-table"></div>
</div>

<script>
const vscode = acquireVsCodeApi();
function refresh() { vscode.postMessage({ command: 'refresh' }); }
function exportSession() { vscode.postMessage({ command: 'exportSession' }); }

let _allSessions = [];
let _days = [];
let _currentProject = '';

function fmtK(n) {
  if (n >= 1e6) return (n/1e6).toFixed(1)+'M';
  if (n >= 1e3) return (n/1e3).toFixed(0)+'K';
  return n+'';
}
function fmtCost(c) { return c < 0.01 ? '<$0.01' : '$'+c.toFixed(2); }
function relTime(ts) {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff/60000);
  if (m < 1) return 'just now';
  if (m < 60) return m+'m ago';
  const h = Math.floor(m/60);
  if (h < 24) return h+'h ago';
  return Math.floor(h/24)+'d ago';
}

// Readable session label: "project / MM-DD HH:mm" — slug shown on hover
function sessionLabel(s) {
  const d = new Date(s.firstTs);
  const mm = String(d.getMonth()+1).padStart(2,'0');
  const dd = String(d.getDate()).padStart(2,'0');
  const hh = String(d.getHours()).padStart(2,'0');
  const mi = String(d.getMinutes()).padStart(2,'0');
  return \`\${s.project} / \${mm}-\${dd} \${hh}:\${mi}\`;
}

function applyFilter() {
  const sel = document.getElementById('project-filter').value;
  renderSessions(sel ? _allSessions.filter(s => s.project === sel) : _allSessions);
}

function renderSessions(sessions) {
  document.getElementById('sessions-table').innerHTML = sessions.length === 0
    ? '<p class="empty">No sessions match</p>'
    : \`<table>
      <tr><th>Session</th><th>Model</th><th>Turns</th><th>Tok/turn</th><th>In</th><th>Out</th><th>Cache%</th><th>Ctx%</th><th>Cost</th><th>Last</th></tr>
      \${sessions.slice(0,30).map(s => {
        const totalIn = s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens;
        const cacheHit = totalIn > 0 ? Math.round(s.cacheReadTokens/totalIn*100) : 0;
        const ctxColor = s.contextPct >= 80 ? 'var(--red)' : s.contextPct >= 60 ? 'var(--yellow)' : 'inherit';
        return \`<tr title="\${s.slug}">
          <td>\${sessionLabel(s)}</td>
          <td><span class="model-tag">\${s.model.replace('claude-','').replace('-4-6','4.6').replace('-4-5','4.5')}</span></td>
          <td>\${s.turns}</td>
          <td>\${fmtK(s.tokensPerTurn??0)}</td>
          <td>\${fmtK(totalIn)}</td>
          <td>\${fmtK(s.outputTokens)}</td>
          <td>\${cacheHit}%</td>
          <td style="color:\${ctxColor}">\${s.contextPct}%</td>
          <td class="cost">\${fmtCost(s.estimatedCostUsd)}</td>
          <td>\${relTime(s.lastTs)}</td>
        </tr>\`;
      }).join('')}
    </table>\`;
}

window.addEventListener('message', e => {
  const msg = e.data;
  if (msg.type !== 'update') return;
  const { sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency } = msg;

  _allSessions = sessions;
  _days = days;
  _currentProject = currentProject ?? '';

  // Score display
  const scoreContainer = document.getElementById('score-container');
  if (efficiency && efficiency.dailyScore !== undefined) {
    const g = (efficiency.grade || 'C').toLowerCase();
    scoreContainer.innerHTML = \`
      <div class="grade-badge grade-\${g}">\${efficiency.grade}</div>
      <div class="score-label">
        <span class="score-title">Prompt Engineer Score</span>
        <span class="score-val">\${efficiency.dailyScore}/100</span>
      </div>
    \`;
  } else {
    scoreContainer.innerHTML = '';
  }

  // Populate project filter dropdown, preserve current selection
  const filterEl = document.getElementById('project-filter');
  const prevSel = filterEl.value;
  const projects = [...new Set(sessions.map(s => s.project))].sort();
  filterEl.innerHTML = '<option value="">All projects</option>'
    + projects.map(p => \`<option value="\${p}"\${p===prevSel?' selected':''}>\${p}</option>\`).join('');

  // Show active project badge and auto-select current workspace on first load
  const badge = document.getElementById('active-badge');
  if (currentProject) {
    badge.style.display = 'inline';
    badge.textContent = currentProject;
    // Auto-select current workspace only if filter hasn't been manually changed
    if (!prevSel && projects.includes(currentProject)) {
      filterEl.value = currentProject;
    }
  } else {
    badge.style.display = 'none';
  }

  // Summary cards — always across ALL sessions for today (not filtered)
  const today = new Date().toISOString().slice(0,10);
  const todaySessions = sessions.filter(s => s.lastTs.slice(0,10) === today);
  const todayIn   = todaySessions.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const todayOut  = todaySessions.reduce((a,s) => a+s.outputTokens, 0);
  const todayCost = todaySessions.reduce((a,s) => a+s.estimatedCostUsd, 0);
  const latest    = sessions[0] ?? null;

  // Prefer live context % from statusLine if available
  const ctxPct = liveMetrics?.contextPct ?? latest?.contextPct ?? 0;
  const ctxColor = ctxPct >= 80 ? 'var(--red)' : ctxPct >= 60 ? 'var(--yellow)' : 'var(--green)';

  // Cache efficiency across today
  const todayTotalInput = todaySessions.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const todayCacheRead  = todaySessions.reduce((a,s) => a+s.cacheReadTokens, 0);
  const cacheHitPct = todayTotalInput > 0 ? Math.round(todayCacheRead / todayTotalInput * 100) : 0;

  const fiveHourPct  = liveMetrics?.fiveHourPct  ?? null;
  const sevenDayPct  = liveMetrics?.sevenDayPct  ?? null;
  const fiveHourReset = liveMetrics?.fiveHourResetsAt
    ? 'resets '+new Date(liveMetrics.fiveHourResetsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
    : 'subscription limit';

  document.getElementById('cards').innerHTML = [
    card('Today In',  fmtK(todayIn),  todaySessions.length+' sessions · '+fmtCost(todayCost)+' est.'),
    card('Today Out', fmtK(todayOut), 'cache hit '+cacheHitPct+'%'),
    cardWithBar('Context Window', Math.round(ctxPct)+'%', latest ? sessionLabel(latest)+' · '+fmtK(latest.tokensPerTurn??0)+'/turn' : '—', ctxPct, ctxColor),
    fiveHourPct !== null
      ? cardWithBar('5-Hour Limit', Math.round(fiveHourPct)+'%', fiveHourReset,  fiveHourPct, fiveHourPct>=80?'var(--red)':fiveHourPct>=60?'var(--yellow)':'var(--green)')
      : card('Total Sessions', sessions.length+'', sessions.reduce((a,s)=>a+s.turns,0)+' turns total'),
    sevenDayPct !== null
      ? cardWithBar('7-Day Limit', Math.round(sevenDayPct)+'%', 'subscription limit', sevenDayPct, sevenDayPct>=80?'var(--red)':sevenDayPct>=60?'var(--yellow)':'var(--green)')
      : card('Total Sessions', sessions.length+'', sessions.reduce((a,s)=>a+s.turns,0)+' turns total'),
  ].filter((v,i,a) => a.indexOf(v)===i).join(''); // dedup if both rate limit cards are null

  // Activity feed
  const feedEl = document.getElementById('activity-feed');
  if (activity.length === 0) {
    feedEl.innerHTML = '<p class="empty">No activity yet — configure hooks to see live updates</p>';
  } else {
    feedEl.innerHTML = [...activity].reverse().slice(0,30).map(r => {
      const ts = new Date(r.ts).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'});
      const dur = r.durationMs ? (r.durationMs/1000).toFixed(1)+'s' : '';
      const icon = r.event === 'PreToolUse' ? '▶' : r.event === 'PostToolUse' ? '✓' : r.event === 'Stop' ? '■' : '●';
      return \`<div class="activity-item">
        <span class="activity-ts">\${ts}</span>
        <span class="activity-tool">\${icon} \${r.tool ?? r.event}</span>
        <span class="activity-summary">\${r.summary ?? ''}</span>
        <span class="activity-dur">\${dur}</span>
      </div>\`;
    }).join('');
  }

  // Hooks notice
  const noticeEl = document.getElementById('hooks-notice');
  if (!hooksActive) {
    noticeEl.style.display = 'block';
    noticeEl.innerHTML = \`
      <div class="notice">
        <div><strong>Live activity requires hooks.</strong> Your ~/.claude/settings.json needs to be updated.</div>
        <button class="btn-install" onclick="vscode.postMessage({command: 'installHooks'})">1-Click Auto Install</button>
      </div>
    \`;
  } else {
    noticeEl.style.display = 'none';
  }

  // Efficiency section
  renderEfficiency(efficiency, todayIn, todayOut);

  // Sessions table — apply current filter
  applyFilter();

  // Days table
  document.getElementById('days-table').innerHTML = days.length === 0
    ? '<p class="empty">No data</p>'
    : \`<table>
      <tr><th>Date</th><th>Sessions</th><th>Turns</th><th>In</th><th>Out</th><th>Est. Cost</th></tr>
      \${days.slice(0,14).map(d => \`<tr>
        <td>\${d.date === today ? '<strong>Today</strong>' : d.date}</td>
        <td>\${d.sessions}</td>
        <td>\${d.turns}</td>
        <td>\${fmtK(d.inputTokens)}</td>
        <td>\${fmtK(d.outputTokens)}</td>
        <td class="cost">\${fmtCost(d.estimatedCostUsd)}</td>
      </tr>\`).join('')}
    </table>\`;
});

const TOOL_COLORS = {
  Bash: '#4ec9b0', Edit: '#569cd6', Write: '#9cdcfe', Read: '#dcdcaa',
  Grep: '#c586c0', Glob: '#ce9178', WebFetch: '#4fc1ff', Agent: '#f44747',
};

function renderEfficiency(eff, todayIn, todayOut) {
  const el = document.getElementById('efficiency-section');
  if (!eff || eff.totalToolCalls === 0) {
    el.innerHTML = '<p class="empty" style="grid-column:1/-1">No tool activity yet — hooks required for efficiency metrics</p>';
    return;
  }

  // Tool breakdown
  const maxCalls = eff.toolBreakdown[0]?.calls ?? 1;
  const toolRows = eff.toolBreakdown.slice(0, 8).map(s => {
    const color = TOOL_COLORS[s.tool] ?? '#888';
    const pct = Math.round(s.calls / maxCalls * 100);
    const dur = eff.avgToolDurationMs[s.tool]
      ? (eff.avgToolDurationMs[s.tool] >= 1000
          ? (eff.avgToolDurationMs[s.tool]/1000).toFixed(1)+'s'
          : eff.avgToolDurationMs[s.tool]+'ms')
      : '';
    return \`<div class="tool-bar-row">
      <span class="tool-bar-label">\${s.tool}</span>
      <div class="tool-bar-track"><div class="tool-bar-fill" style="width:\${pct}%;background:\${color}"></div></div>
      <span class="tool-bar-count">\${s.calls}</span>
      <span class="tool-bar-dur">\${dur}</span>
    </div>\`;
  }).join('');

  // Stats panel
  const errPct = Math.round(eff.bashErrorRate * 100);
  const errClass = errPct >= 30 ? 'bad' : errPct >= 15 ? 'warn' : 'good';

  const ctxEff = eff.contextEfficiency;
  const ctxEffPct = ctxEff !== null ? Math.round(ctxEff * 100) : null;
  const ctxEffClass = ctxEffPct === null ? '' : ctxEffPct >= 15 ? 'good' : ctxEffPct >= 5 ? 'warn' : 'bad';

  const totalCalls = eff.totalToolCalls;
  const readWritePct = eff.toolBreakdown
    .filter(s => ['Read','Write','Edit'].includes(s.tool))
    .reduce((a,s) => a + s.calls, 0);
  const actionRatio = totalCalls > 0 ? Math.round(readWritePct / totalCalls * 100) : 0;

  const runawayHtml = eff.isRunaway 
    ? \`<div style="background:rgba(244,71,71,0.2); border:1px solid var(--red); color:var(--red); padding:10px; border-radius:8px; margin-bottom:15px; font-size:12px; font-weight:bold; display:flex; align-items:center; gap:8px;">
        <span>⚠️</span> RUNAWAY AGENT DETECTED: High Bash Error Rate
       </div>\` : '';
  
  const budgetHtml = eff.budgetExceeded 
    ? \`<div style="background:rgba(255,165,0,0.2); border:1px solid var(--yellow); color:var(--yellow); padding:10px; border-radius:8px; margin-bottom:15px; font-size:12px; font-weight:bold; display:flex; align-items:center; gap:8px;">
        <span>💰</span> SESSION BUDGET EXCEEDED ($2.00 threshold)
       </div>\` : '';

  el.innerHTML = \`
    <div class="eff-panel">
      <h4>Tool Distribution — \${totalCalls} calls</h4>
      \${toolRows}
    </div>
    <div class="eff-panel">
      <h4>Session Introspection</h4>
      \${runawayHtml}
      \${budgetHtml}
      <div class="stat-row">
        <span>Bash error rate</span>
        <span class="stat-val \${errClass}">\${errPct}%</span>
      </div>
      <div class="stat-row">
        <span>Context efficiency</span>
        <span class="stat-val \${ctxEffClass}">\${ctxEffPct !== null ? ctxEffPct+'% output/input' : '—'}</span>
      </div>
      <div class="stat-row">
        <span>Action ratio (Read/Write/Edit)</span>
        <span class="stat-val">\${actionRatio}%</span>
      </div>
      <div class="stat-row">
        <span>Unique tools used</span>
        <span class="stat-val">\${eff.toolBreakdown.length}</span>
      </div>
      <div class="stat-row" style="margin-top:8px;padding-top:8px;border-top:1px solid var(--border)">
        <span style="font-size:10px;color:var(--muted)" colspan="2">
          High error rate → Claude thrashing on shell cmds<br/>
          Low ctx efficiency → lots of reading, little output<br/>
          High action ratio → editing-heavy session
        </span>
      </div>
    </div>
    <div class="eff-panel">
      <h4>Estimated Time Saved (Day)</h4>
      <div class="stat-row">
        <span>Automated Typing</span>
        <span class="stat-val good">+\${Math.round((todayOut || 0) * 0.75 / 60)} mins</span>
      </div>
      <div class="stat-row">
        <span>Fast-reading Context</span>
        <span class="stat-val good">+\${Math.round((todayIn || 0) * 0.75 / 250)} mins</span>
      </div>
      <div class="stat-row">
        <span>Executing Tools</span>
        <span class="stat-val good">+\${Math.round(totalCalls * 1.5)} mins</span>
      </div>
      <div class="stat-row" style="background: rgba(78, 201, 176, 0.1); border: 1px solid var(--green); padding: 12px; border-radius: 8px; margin-top: 16px;">
        <span style="font-weight: 700; color: var(--green);">Total Time Saved</span>
        <span style="font-size: 18px; font-weight: 800; color: var(--green);">
          \${(() => {
            const m = ((todayIn || 0) * 0.75 / 250) + ((todayOut || 0) * 0.75 / 60) + (totalCalls * 1.5);
            const h = Math.floor(m / 60);
            return h > 0 ? h + 'h ' + Math.floor(m % 60) + 'm' : Math.floor(m % 60) + 'm';
          })()}
        </span>
      </div>
      <div class="stat-row" style="margin-top:12px;padding-top:12px;border-top:none;justify-content:center;background:transparent;">
        <span style="font-size:10px;color:var(--muted);text-align:center">
          *Math: 250wpm reading, 60wpm typing,<br/>1.5m context-switch per tool action (Today)
        </span>
      </div>
    </div>
  \`;

  // File Heatmap
  if (eff.fileStats && Object.keys(eff.fileStats).length > 0) {
    const sortedFiles = Object.entries(eff.fileStats)
      .sort((a,b) => b[1] - a[1])
      .slice(0, 10);
    
    const heatmapHtml = sortedFiles.map(([path, count]) => {
      const opacity = Math.min(1, 0.2 + (count / sortedFiles[0][1] * 0.8));
      return \`<div class="stat-row" style="background:rgba(0,122,204,\${opacity/5}); padding:8px 12px; border-radius:6px; margin-bottom:4px; border-bottom:none">
        <span style="font-family:monospace; color:var(--fg); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; flex:1">\${path}</span>
        <span style="font-weight:bold; color:var(--accent); min-width:40px; text-align:right">\${count}x</span>
      </div>\`;
    }).join('');

    el.innerHTML += \`
      <div class="eff-panel" style="grid-column: 1 / -1; margin-top: 24px;">
        <h4>File Access Heatmap (Top 10)</h4>
        <div style="display:grid; grid-template-columns: 1fr 1fr; gap: 12px;">
          \${heatmapHtml}
        </div>
      </div>
    \`;
  }
}

function card(label, value, sub) {
  return \`<div class="card"><div class="card-label">\${label}</div><div class="card-value">\${value}</div><div class="card-sub">\${sub}</div></div>\`;
}
function cardWithBar(label, value, sub, pct, color) {
  return \`<div class="card">
    <div class="card-label">\${label}</div>
    <div class="card-value" style="color:\${color}">\${value}</div>
    <div style="margin:4px 0;height:4px;background:var(--border);border-radius:2px">
      <div style="height:100%;width:\${pct}%;background:\${color};border-radius:2px;transition:width .3s"></div>
    </div>
    <div class="card-sub">\${sub}</div>
  </div>\`;
}
</script>
</body>
</html>`;
  }
}
