import * as vscode from 'vscode';
import { SessionSummary, DaySummary, ActivityRecord, EfficiencyStats } from './types';

export class UsageDashboardPanel implements vscode.Disposable {
  static currentPanel: UsageDashboardPanel | undefined;

  private readonly panel: vscode.WebviewPanel;
  private disposables: vscode.Disposable[] = [];
  
  private lastActivity: ActivityRecord[] = [];
  private lastProject?: string;
  private lastEfficiency?: EfficiencyStats;

  static show(): UsageDashboardPanel {
    if (UsageDashboardPanel.currentPanel) {
      UsageDashboardPanel.currentPanel.panel.reveal();
      return UsageDashboardPanel.currentPanel;
    }
    const panel = vscode.window.createWebviewPanel(
      'claudeUsageDashboard',
      'Claude Usage',
      vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    UsageDashboardPanel.currentPanel = new UsageDashboardPanel(panel);
    return UsageDashboardPanel.currentPanel;
  }

  private constructor(panel: vscode.WebviewPanel) {
    this.panel = panel;
    this.panel.onDidDispose(() => this.dispose(), null, this.disposables);
    this.panel.webview.onDidReceiveMessage(message => {
      if (message.command === 'installHooks') {
        vscode.commands.executeCommand('claudeUsage.installHooks');
      } else if (message.command === 'refresh' || message.command === 'ready') {
        vscode.commands.executeCommand('claudeUsage.refresh');
      }
    }, undefined, this.disposables);
    this.panel.webview.html = this.skeleton();
  }

  update(
    sessions: SessionSummary[], days: DaySummary[], activity: ActivityRecord[],
    hooksActive: boolean, currentProject?: string,
    liveMetrics?: { contextPct: number | null; fiveHourPct: number | null; sevenDayPct: number | null; fiveHourResetsAt: Date | null },
    efficiency?: EfficiencyStats
  ): void {
    this.lastActivity = activity;
    this.lastProject = currentProject;
    this.lastEfficiency = efficiency;
    this.panel.webview.postMessage({ type: 'update', sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency });
  }

  private async exportSessionToMarkdown(): Promise<void> {
    if (this.lastActivity.length === 0) {
      vscode.window.showWarningMessage('No activity data to export.');
      return;
    }

    let md = `# Claude Session Export: ${this.lastProject || 'Untracked Project'}\n`;
    md += `*Generated by Claude Usage Monitor*\n\n`;
    
    if (this.lastEfficiency) {
      md += `## Efficiency Stats\n`;
      md += `- **Total Tool Calls:** ${this.lastEfficiency.totalToolCalls}\n`;
      md += `- **Bash Error Rate:** ${Math.round(this.lastEfficiency.bashErrorRate * 100)}%\n`;
      if (this.lastEfficiency.sessionCostUsd) {
        md += `- **Estimated Cost (Today):** $${this.lastEfficiency.sessionCostUsd.toFixed(2)}\n`;
      }
      md += `\n`;
    }

    md += `## Tool Usage Sequence\n\n`;
    md += `| Timestamp | Event | Tool | Summary | Duration |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    // Process records - group Pre/Post if possible or just list them
    for (const r of this.lastActivity) {
      const time = new Date(r.ts).toLocaleTimeString();
      const dur = r.durationMs ? `${(r.durationMs / 1000).toFixed(1)}s` : '-';
      const event = r.event === 'PreToolUse' ? '▶ Start' : r.event === 'PostToolUse' ? '✓ End' : r.event;
      md += `| ${time} | ${event} | \`${r.tool || '-'}\` | ${r.summary || '-'} | ${dur} |\n`;
    }

    md += `\n\n--- \n*Use this log to reconcile your Anthropic billing or to document AI-driven architectural changes.*`;

    const doc = await vscode.workspace.openTextDocument({
      content: md,
      language: 'markdown'
    });
    await vscode.window.showTextDocument(doc);
  }

  reveal(): void {
    this.panel.reveal();
  }

  dispose(): void {
    UsageDashboardPanel.currentPanel = undefined;
    this.panel.dispose();
    this.disposables.forEach(d => d.dispose());
  }

  private skeleton(): string {
    return /* html */`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Claude Usage</title>
<style>
  :root {
    --bg: var(--vscode-editor-background);
    --fg: var(--vscode-editor-foreground);
    --border: var(--vscode-panel-border, #2a2a2a);
    --card-bg: var(--vscode-sideBar-background, #1a1a1a);
    --accent: var(--vscode-focusBorder, #007acc);
    --accent-hover: var(--vscode-textLink-activeForeground, #005a9e);
    --muted: var(--vscode-descriptionForeground, #666);
    --green: #4ec9b0;
    --yellow: #dcdcaa;
    --red: #f44747;
    --glass-bg: rgba(255,255,255,0.02);
    --glass-border: rgba(255,255,255,0.05);
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: var(--vscode-font-family); font-size: 11px; color: var(--fg); background: var(--bg); padding: 12px 14px; max-width: 1200px; margin: 0 auto; }

  h2 { font-size: 13px; font-weight: 700; display: flex; align-items: center; gap: 8px; }
  h3 { font-size: 10px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: .8px; }
  h4 { font-size: 10px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: .6px; margin-bottom: 8px; padding-bottom: 5px; border-bottom: 1px solid var(--glass-border); }

  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid var(--border); }
  button { background: var(--card-bg); color: var(--fg); border: 1px solid var(--border); padding: 3px 9px; border-radius: 4px; cursor: pointer; font-size: 11px; transition: border-color .15s; }
  button:hover { border-color: var(--accent); }
  button.primary { background: var(--accent); color: #fff; border-color: var(--accent); }

  /* Cards */
  .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 8px; margin-bottom: 12px; animation: fadeIn .3s ease; }
  .card { background: var(--card-bg); border: 1px solid var(--glass-border); border-radius: 5px; padding: 10px 12px; cursor: default; }
  .card-label { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: .4px; margin-bottom: 3px; }
  .card-value { font-size: 18px; font-weight: 700; line-height: 1.1; }
  .card-sub { font-size: 10px; color: var(--muted); margin-top: 3px; }

  /* Collapsible section */
  .section { margin-bottom: 8px; border: 1px solid var(--glass-border); border-radius: 5px; overflow: hidden; }
  .section-header { display: flex; align-items: center; justify-content: space-between; padding: 7px 10px; cursor: pointer; user-select: none; background: var(--glass-bg); }
  .section-header:hover { background: rgba(255,255,255,0.03); }
  .section-header h3 { margin: 0; }
  .section-header .toggle { font-size: 9px; color: var(--muted); transition: transform .2s; }
  .section-header.collapsed .toggle { transform: rotate(-90deg); }
  .section-body { padding: 10px 12px; }
  .section-body.hidden { display: none; }

  /* Tables */
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { text-align: left; padding: 4px 8px; color: var(--muted); font-weight: 600; border-bottom: 1px solid var(--border); white-space: nowrap; }
  td { padding: 4px 8px; border-bottom: 1px solid var(--glass-border); vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  .model-tag { font-size: 10px; padding: 1px 5px; border-radius: 8px; background: rgba(0,122,204,.15); border: 1px solid rgba(0,122,204,.25); color: var(--accent); }
  .cost { color: var(--yellow); }

  /* Grade */
  .grade-badge { width: 28px; height: 28px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 900; color: #fff; }
  .grade-s { background: linear-gradient(135deg,#ffd700,#ff8c00); }
  .grade-a { background: linear-gradient(135deg,#4ec9b0,#007acc); }
  .grade-b { background: linear-gradient(135deg,#007acc,#c586c0); }
  .grade-c { background: linear-gradient(135deg,#888,#555); }
  .grade-f { background: linear-gradient(135deg,#f44747,#b22222); }

  /* Notice */
  .notice { display: flex; align-items: center; justify-content: space-between; gap: 10px; padding: 7px 10px; background: rgba(244,71,71,.08); border-left: 3px solid var(--red); border-radius: 0 4px 4px 0; font-size: 11px; margin-bottom: 8px; }
  .btn-install { background: var(--green); color: #000; border: none; padding: 3px 9px; border-radius: 4px; font-weight: 600; cursor: pointer; font-size: 11px; white-space: nowrap; }

  /* Efficiency */
  .eff-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }
  .tool-bar-row { display: flex; align-items: center; gap: 6px; margin-bottom: 5px; }
  .tool-bar-label { width: 64px; flex-shrink: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .tool-bar-track { flex: 1; height: 6px; background: rgba(0,0,0,0.25); border-radius: 3px; overflow: hidden; }
  .tool-bar-fill { height: 100%; border-radius: 3px; transition: width .5s cubic-bezier(.1,.8,.2,1); }
  .tool-bar-count { width: 24px; text-align: right; color: var(--muted); }
  .tool-bar-dur { width: 34px; text-align: right; color: var(--muted); }
  .stat-row { display: flex; justify-content: space-between; align-items: center; padding: 4px 0; border-bottom: 1px solid var(--glass-border); }
  .stat-row:last-child { border-bottom: none; }
  .stat-label { display: flex; align-items: center; gap: 4px; }
  .stat-val { font-weight: 700; }
  .stat-val.good { color: var(--green); }
  .stat-val.warn { color: var(--yellow); }
  .stat-val.bad  { color: var(--red); }
  .alert-pill { display: inline-flex; align-items: center; gap: 5px; padding: 3px 7px; border-radius: 3px; font-size: 10px; font-weight: 600; margin-bottom: 5px; }
  .alert-pill.runaway { background: rgba(244,71,71,.15); color: var(--red); border: 1px solid rgba(244,71,71,.3); }
  .alert-pill.budget  { background: rgba(220,220,170,.15); color: var(--yellow); border: 1px solid rgba(220,220,170,.3); }
  .total-row { display: flex; justify-content: space-between; align-items: center; padding: 6px 8px; border-radius: 4px; background: rgba(78,201,176,.08); border: 1px solid rgba(78,201,176,.2); margin-top: 8px; }

  /* Filter */
  .filter-row { display: flex; align-items: center; gap: 6px; }
  .filter-row select { background: var(--bg); color: var(--fg); border: 1px solid var(--border); border-radius: 4px; padding: 2px 6px; font-size: 11px; cursor: pointer; outline: none; }
  .project-badge { font-size: 10px; padding: 1px 6px; border-radius: 8px; background: var(--accent); color: #fff; font-weight: 600; }

  /* Day trend chart */
  .chart-wrap { position: relative; }
  .chart-tooltip { position: absolute; background: var(--card-bg); border: 1px solid var(--border); border-radius: 4px; padding: 4px 8px; font-size: 10px; pointer-events: none; display: none; white-space: nowrap; z-index: 10; }
  svg.trend text { font-family: var(--vscode-font-family); }

  /* Range tabs */
  .range-tabs { display: flex; border: 1px solid var(--border); border-radius: 4px; overflow: hidden; }
  .range-btn { background: transparent; border: none; border-radius: 0; padding: 3px 8px; font-size: 10px; color: var(--muted); cursor: pointer; transition: background .15s,color .15s; }
  .range-btn:hover { background: rgba(255,255,255,0.05); color: var(--fg); }
  .range-btn.active { background: var(--accent); color: #fff; }

  /* GitHub-style heatmap */
  .heatmap-wrap { overflow-x: auto; }
  .heatmap-grid { display: flex; gap: 3px; align-items: flex-start; }
  .heatmap-col { display: flex; flex-direction: column; gap: 3px; }
  .heatmap-cell { width: 12px; height: 12px; border-radius: 2px; cursor: pointer; }
  .heatmap-labels { display: flex; gap: 3px; margin-bottom: 3px; }
  .heatmap-month { font-size: 9px; color: var(--muted); }
  .heatmap-day-labels { display: flex; flex-direction: column; gap: 3px; margin-right: 4px; padding-top: 0; }
  .heatmap-day-label { font-size: 9px; color: var(--muted); height: 12px; line-height: 12px; text-align: right; }
  .heatmap-legend { display: flex; align-items: center; gap: 4px; margin-top: 6px; justify-content: flex-end; }
  .heatmap-legend-label { font-size: 9px; color: var(--muted); }
  .heatmap-cell.l0 { background: var(--glass-bg); border: 1px solid var(--glass-border); }
  .heatmap-cell.l1 { background: #0e4429; }
  .heatmap-cell.l2 { background: #006d32; }
  .heatmap-cell.l3 { background: #26a641; }
  .heatmap-cell.l4 { background: #39d353; }

  /* Hover tooltip */
  .tip { position: fixed; background: var(--card-bg); border: 1px solid var(--border); border-radius: 4px; padding: 6px 9px; font-size: 10px; line-height: 1.5; pointer-events: none; display: none; white-space: pre-line; z-index: 100; max-width: 240px; color: var(--fg); box-shadow: 0 4px 12px rgba(0,0,0,.4); }
  [data-tip] { cursor: help; }
  .tip-icon { font-size: 9px; color: var(--muted); opacity: .6; }

  .empty { color: var(--muted); font-size: 11px; padding: 20px; text-align: center; }
  @keyframes fadeIn { from { opacity:0 } to { opacity:1 } }
</style>
</head>
<body>
<div class="header">
  <div style="display:flex;align-items:center;gap:10px">
    <h2>⚡ Claude Usage</h2>
    <div id="score-container" style="display:flex;align-items:center;gap:6px;border-left:1px solid var(--border);padding-left:10px"></div>
  </div>
  <div style="display:flex;align-items:center;gap:6px">
    <div class="range-tabs">
      <button class="range-btn" data-range="1" onclick="setRange(1)">Today</button>
      <button class="range-btn" data-range="7" onclick="setRange(7)">7d</button>
      <button class="range-btn" data-range="30" onclick="setRange(30)">30d</button>
    </div>
    <button class="primary" onclick="refresh()">↻</button>
  </div>
</div>

<div id="cards" class="cards"></div>
<div id="hooks-notice"></div>

<div class="section">
  <div class="section-header" onclick="toggleSection(this)">
    <h3>Efficiency</h3>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body">
    <div id="efficiency-section" class="eff-grid"></div>
  </div>
</div>

<div class="section">
  <div class="section-header collapsed" onclick="toggleSection(this)">
    <div class="filter-row">
      <h3>Sessions</h3>
      <select id="project-filter" onchange="applyFilter()" onclick="event.stopPropagation()">
        <option value="">All projects</option>
      </select>
      <span id="active-badge" style="display:none" class="project-badge"></span>
    </div>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body hidden">
    <div id="sessions-table"></div>
  </div>
</div>

<div class="section">
  <div class="section-header" onclick="toggleSection(this)">
    <h3>Activity Heatmap</h3>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body">
    <div class="chart-wrap">
      <div id="chart-tooltip" class="chart-tooltip"></div>
      <div id="day-chart"></div>
    </div>
  </div>
</div>

<div id="tip" class="tip"></div>

<script>
const vscode = acquireVsCodeApi();
function refresh() { vscode.postMessage({ command: 'refresh' }); }

// Signal the extension that the webview is ready — request initial data push
vscode.postMessage({ command: 'ready' });

function toggleSection(header) {
  header.classList.toggle('collapsed');
  const body = header.nextElementSibling;
  if (body) body.classList.toggle('hidden');
}

// Global hover tooltip — any element with data-tip shows an explanation
const _tip = document.getElementById('tip');
document.addEventListener('mouseover', e => {
  const el = e.target.closest('[data-tip]');
  if (!el) return;
  _tip.textContent = el.dataset.tip;
  _tip.style.display = 'block';
});
document.addEventListener('mousemove', e => {
  if (_tip.style.display === 'none') return;
  const x = e.clientX + 14, y = e.clientY + 12;
  const maxX = window.innerWidth  - _tip.offsetWidth  - 8;
  const maxY = window.innerHeight - _tip.offsetHeight - 8;
  _tip.style.left = Math.min(x, maxX) + 'px';
  _tip.style.top  = Math.min(y, maxY) + 'px';
});
document.addEventListener('mouseout', e => {
  if (!e.target.closest('[data-tip]')) return;
  _tip.style.display = 'none';
});

let _allSessions = [];
let _days = [];
let _currentProject = '';

// Range selection — persisted in localStorage
let _rangeDays = parseInt(localStorage.getItem('claudeUsage.range') || '7', 10);

function setRange(days) {
  _rangeDays = days;
  localStorage.setItem('claudeUsage.range', days);
  document.querySelectorAll('.range-btn').forEach(b => {
    b.classList.toggle('active', parseInt(b.dataset.range) === days);
  });
  renderCardsForRange();
  applyFilter();
}

function initRange() {
  document.querySelectorAll('.range-btn').forEach(b => {
    b.classList.toggle('active', parseInt(b.dataset.range) === _rangeDays);
  });
}

function sessionsInRange() {
  const cutoff = new Date(Date.now() - _rangeDays * 86400000).toISOString();
  return _allSessions.filter(s => s.lastTs >= cutoff);
}

function renderCardsForRange() {
  // Re-render cards using current range — called when range changes without new data
  if (!_allSessions.length && !_days.length) return;
  const today = new Date().toISOString().slice(0,10);
  const ranged = sessionsInRange();
  const rIn    = ranged.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const rOut   = ranged.reduce((a,s) => a+s.outputTokens, 0);
  const rCost  = ranged.reduce((a,s) => a+s.estimatedCostUsd, 0);
  const rCache = ranged.reduce((a,s) => a+s.cacheReadTokens, 0);
  const rTotIn = ranged.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const cacheHit = rTotIn > 0 ? Math.round(rCache/rTotIn*100) : 0;
  const label = _rangeDays === 1 ? 'Today' : \`\${_rangeDays}d\`;
  document.getElementById('cards').innerHTML = buildCards(ranged, rIn, rOut, rCost, cacheHit, label, today);
}

function fmtK(n) {
  if (n >= 1e6) return (n/1e6).toFixed(1)+'M';
  if (n >= 1e3) return (n/1e3).toFixed(0)+'K';
  return n+'';
}
function fmtCost(c) { return c < 0.01 ? '<$0.01' : '$'+c.toFixed(2); }
function relTime(ts) {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff/60000);
  if (m < 1) return 'just now';
  if (m < 60) return m+'m ago';
  const h = Math.floor(m/60);
  if (h < 24) return h+'h ago';
  return Math.floor(h/24)+'d ago';
}

// Readable session label: "project / MM-DD HH:mm" — slug shown on hover
function sessionLabel(s) {
  const d = new Date(s.firstTs);
  const mm = String(d.getMonth()+1).padStart(2,'0');
  const dd = String(d.getDate()).padStart(2,'0');
  const hh = String(d.getHours()).padStart(2,'0');
  const mi = String(d.getMinutes()).padStart(2,'0');
  return \`\${s.project} / \${mm}-\${dd} \${hh}:\${mi}\`;
}

function applyFilter() {
  const sel = document.getElementById('project-filter').value;
  const inRange = sessionsInRange();
  renderSessions(sel ? inRange.filter(s => s.project === sel) : inRange);
}

function buildCards(ranged, rIn, rOut, rCost, cacheHit, label, today, latest, liveMetrics, allSessions, fiveHourPct, sevenDayPct) {
  latest = latest ?? (allSessions && allSessions[0]) ?? null;
  const ctxPct = (liveMetrics && liveMetrics.contextPct != null) ? liveMetrics.contextPct : (latest?.contextPct ?? 0);
  const ctxColor = ctxPct >= 80 ? 'var(--red)' : ctxPct >= 60 ? 'var(--yellow)' : 'var(--green)';
  const fiveHourReset = (liveMetrics && liveMetrics.fiveHourResetsAt)
    ? 'resets '+new Date(liveMetrics.fiveHourResetsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
    : 'subscription limit';
  const totalSessions = allSessions ? allSessions.length : 0;
  const totalTurns = allSessions ? allSessions.reduce((a,s)=>a+s.turns,0) : 0;
  return [
    card(label+' In',  fmtK(rIn),  ranged.length+' sessions \xB7 '+fmtCost(rCost)+' est.',
      'Tokens sent TO Claude in selected range.&#10;Includes input + cache reads + cache writes.&#10;High input = lots of context re-sent each turn.'),
    card(label+' Out', fmtK(rOut), 'cache hit '+cacheHit+'%',
      'Tokens generated BY Claude in selected range.&#10;Cache hit % = share of input served from cache (saves cost).&#10;Higher cache hit = more efficient prompting.'),
    cardWithBar('Context', Math.round(ctxPct)+'%', latest ? fmtK(latest.tokensPerTurn??0)+'/turn' : '—', ctxPct, ctxColor,
      'How full the active session context is (max 200K tokens).&#10;>60% = approaching limit, consider /compact.&#10;>80% = risk of truncation or degraded responses.'),
    fiveHourPct !== null
      ? cardWithBar('5h Limit', Math.round(fiveHourPct)+'%', fiveHourReset, fiveHourPct, fiveHourPct>=80?'var(--red)':fiveHourPct>=60?'var(--yellow)':'var(--green)',
          'Rolling 5-hour usage cap for Claude subscriptions.&#10;Resets automatically. If this hits 100% Claude stops responding until reset.')
      : card('Sessions', totalSessions+'', totalTurns+' turns total',
          'Total JSONL session files found in ~/.claude/projects/.&#10;Each session = one Claude conversation thread.'),
    sevenDayPct !== null
      ? cardWithBar('7d Limit', Math.round(sevenDayPct)+'%', 'subscription limit', sevenDayPct, sevenDayPct>=80?'var(--red)':sevenDayPct>=60?'var(--yellow)':'var(--green)',
          '7-day rolling usage cap for Claude subscriptions.&#10;Resets weekly. High usage here may indicate runaway agents or very long sessions.')
      : card('Sessions', totalSessions+'', totalTurns+' turns total',
          'Total JSONL session files found in ~/.claude/projects/.&#10;Each session = one Claude conversation thread.'),
  ].filter((v,i,a) => a.indexOf(v)===i).join('');
}

function renderSessions(sessions) {
  document.getElementById('sessions-table').innerHTML = sessions.length === 0
    ? '<p class="empty">No sessions match</p>'
    : \`<table>
      <tr><th>Session</th><th>Model</th><th>Turns</th><th>Tok/turn</th><th>In</th><th>Out</th><th>Cache%</th><th>Ctx%</th><th>Cost</th><th>Last</th></tr>
      \${sessions.slice(0,30).map(s => {
        const totalIn = s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens;
        const cacheHit = totalIn > 0 ? Math.round(s.cacheReadTokens/totalIn*100) : 0;
        const ctxColor = s.contextPct >= 80 ? 'var(--red)' : s.contextPct >= 60 ? 'var(--yellow)' : 'inherit';
        return \`<tr title="\${s.slug}">
          <td>\${sessionLabel(s)}</td>
          <td><span class="model-tag">\${s.model.replace('claude-','').replace('-4-6','4.6').replace('-4-5','4.5')}</span></td>
          <td>\${s.turns}</td>
          <td>\${fmtK(s.tokensPerTurn??0)}</td>
          <td>\${fmtK(totalIn)}</td>
          <td>\${fmtK(s.outputTokens)}</td>
          <td>\${cacheHit}%</td>
          <td style="color:\${ctxColor}">\${s.contextPct}%</td>
          <td class="cost">\${fmtCost(s.estimatedCostUsd)}</td>
          <td>\${relTime(s.lastTs)}</td>
        </tr>\`;
      }).join('')}
    </table>\`;
}

window.addEventListener('message', e => {
  const msg = e.data;
  if (msg.type !== 'update') return;
  const { sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency } = msg;

  _allSessions = sessions;
  _days = days;
  _currentProject = currentProject ?? '';

  // Score display
  const scoreContainer = document.getElementById('score-container');
  if (efficiency && efficiency.dailyScore !== undefined) {
    const g = (efficiency.grade || 'C').toLowerCase();
    scoreContainer.innerHTML = \`
      <div class="grade-badge grade-\${g}" data-tip="Prompt Engineer Score: \${efficiency.dailyScore}/100&#10;Based on bash error rate, context efficiency, tool diversity.&#10;S=elite  A=great  B=good  C=average  F=needs work">\${efficiency.grade}</div>
      <span style="color:var(--muted)">\${efficiency.dailyScore}/100</span>
    \`;
  } else {
    scoreContainer.innerHTML = '';
  }

  // Populate project filter dropdown, preserve current selection
  const filterEl = document.getElementById('project-filter');
  const prevSel = filterEl.value;
  const projects = [...new Set(sessions.map(s => s.project))].sort();
  filterEl.innerHTML = '<option value="">All projects</option>'
    + projects.map(p => \`<option value="\${p}"\${p===prevSel?' selected':''}>\${p}</option>\`).join('');

  // Show active project badge and auto-select current workspace on first load
  const badge = document.getElementById('active-badge');
  if (currentProject) {
    badge.style.display = 'inline';
    badge.textContent = currentProject;
    // Auto-select current workspace only if filter hasn't been manually changed
    if (!prevSel && projects.includes(currentProject)) {
      filterEl.value = currentProject;
    }
  } else {
    badge.style.display = 'none';
  }

  initRange();

  const today = new Date().toISOString().slice(0,10);
  const latest = sessions[0] ?? null;

  // Range-based summary cards
  const ranged    = sessionsInRange();
  const rangedIn  = ranged.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const rangedOut = ranged.reduce((a,s) => a+s.outputTokens, 0);
  const rangedCost= ranged.reduce((a,s) => a+s.estimatedCostUsd, 0);
  const rangedCacheRead = ranged.reduce((a,s) => a+s.cacheReadTokens, 0);
  const rangedTotIn = ranged.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const cacheHitPct = rangedTotIn > 0 ? Math.round(rangedCacheRead/rangedTotIn*100) : 0;
  const rangeLabel = _rangeDays === 1 ? 'Today' : \`\${_rangeDays}d\`;

  const ctxPct = liveMetrics?.contextPct ?? latest?.contextPct ?? 0;
  const fiveHourPct = liveMetrics?.fiveHourPct ?? null;
  const sevenDayPct = liveMetrics?.sevenDayPct ?? null;

  document.getElementById('cards').innerHTML = buildCards(ranged, rangedIn, rangedOut, rangedCost, cacheHitPct, rangeLabel, today, latest, liveMetrics, sessions, fiveHourPct, sevenDayPct);

  // Hooks notice
  const noticeEl = document.getElementById('hooks-notice');
  if (!hooksActive) {
    noticeEl.style.display = 'block';
    noticeEl.innerHTML = \`
      <div class="notice">
        <div><strong>Live activity requires hooks.</strong> Your ~/.claude/settings.json needs to be updated.</div>
        <button class="btn-install" onclick="vscode.postMessage({command: 'installHooks'})">1-Click Auto Install</button>
      </div>
    \`;
  } else {
    noticeEl.style.display = 'none';
  }

  // Efficiency section — use range-based in/out
  renderEfficiency(efficiency, rangedIn, rangedOut);

  // Sessions table — apply current filter
  applyFilter();

  // Activity heatmap
  renderHeatmap(days);
});

const TOOL_COLORS = {
  Bash: '#4ec9b0', Edit: '#569cd6', Write: '#9cdcfe', Read: '#dcdcaa',
  Grep: '#c586c0', Glob: '#ce9178', WebFetch: '#4fc1ff', Agent: '#f44747',
};

function renderEfficiency(eff, todayIn, todayOut) {
  const el = document.getElementById('efficiency-section');
  if (!eff) {
    el.innerHTML = '<p class="empty" style="grid-column:1/-1">No efficiency data — hooks required</p>';
    return;
  }
  const noActivity = eff.totalToolCalls === 0;

  // Tool breakdown
  const maxCalls = eff.toolBreakdown[0]?.calls ?? 1;
  const toolRows = noActivity
    ? '<p class="empty" style="padding:16px 0">No tool calls yet this session</p>'
    : eff.toolBreakdown.slice(0, 8).map(s => {
        const color = TOOL_COLORS[s.tool] ?? '#888';
        const pct = Math.round(s.calls / maxCalls * 100);
        const dur = eff.avgToolDurationMs[s.tool]
          ? (eff.avgToolDurationMs[s.tool] >= 1000
              ? (eff.avgToolDurationMs[s.tool]/1000).toFixed(1)+'s'
              : eff.avgToolDurationMs[s.tool]+'ms')
          : '';
        return \`<div class="tool-bar-row">
          <span class="tool-bar-label">\${s.tool}</span>
          <div class="tool-bar-track"><div class="tool-bar-fill" style="width:\${pct}%;background:\${color}"></div></div>
          <span class="tool-bar-count">\${s.calls}</span>
          <span class="tool-bar-dur">\${dur}</span>
        </div>\`;
      }).join('');

  // Stats panel
  const totalCalls = eff.totalToolCalls;
  const errPct = noActivity ? null : Math.round(eff.bashErrorRate * 100);
  const errClass = errPct === null ? '' : errPct >= 30 ? 'bad' : errPct >= 15 ? 'warn' : 'good';

  const ctxEff = eff.contextEfficiency;
  const ctxEffPct = (ctxEff !== null && !noActivity) ? Math.round(ctxEff * 100) : null;
  const ctxEffClass = ctxEffPct === null ? '' : ctxEffPct >= 15 ? 'good' : ctxEffPct >= 5 ? 'warn' : 'bad';

  const readWritePct = eff.toolBreakdown
    .filter(s => ['Read','Write','Edit'].includes(s.tool))
    .reduce((a,s) => a + s.calls, 0);
  const actionRatio = totalCalls > 0 ? Math.round(readWritePct / totalCalls * 100) : null;

  const alertsHtml = [
    eff.isRunaway  ? \`<div class="alert-pill runaway">⚠ High Bash error rate — possible runaway agent</div>\` : '',
    eff.budgetExceeded ? \`<div class="alert-pill budget">💰 Session cost exceeded $2.00 threshold</div>\` : '',
  ].join('');

  const timeSaved = (() => {
    const m = ((todayIn||0)*0.75/250) + ((todayOut||0)*0.75/60) + (totalCalls*1.5);
    if (m < 1) return '—';
    const h = Math.floor(m/60);
    return h > 0 ? h+'h '+Math.floor(m%60)+'m' : Math.floor(m)+'m';
  })();

  el.innerHTML = \`
    <div class="eff-panel">
      <h4>Tool Distribution — \${totalCalls} calls</h4>
      \${toolRows}
    </div>
    <div class="eff-panel">
      <h4>Session Health</h4>
      \${alertsHtml}
      <div class="stat-row" data-tip="% of Bash tool calls that returned non-zero exit code.\n>30% = Claude thrashing on shell commands.\n>15% = worth reviewing the session.">
        <span class="stat-label">Bash error rate <span class="tip-icon">?</span></span>
        <span class="stat-val \${errClass}">\${errPct !== null ? errPct+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Output tokens ÷ input tokens.\nHigher = Claude producing more per token consumed.\nLow (5%) = mostly reading, little writing.\nGood (15%+) = solid generation-to-consumption ratio.">
        <span class="stat-label">Context efficiency <span class="tip-icon">?</span></span>
        <span class="stat-val \${ctxEffClass}">\${ctxEffPct !== null ? ctxEffPct+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="% of tool calls spent on file operations (Read/Write/Edit).\nHigh = file-editing-heavy session.\nLow = more search/bash/web activity.">
        <span class="stat-label">File op ratio <span class="tip-icon">?</span></span>
        <span class="stat-val">\${actionRatio !== null ? actionRatio+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Number of distinct tools used in this session.\nHigher diversity = Claude using the full toolkit.\nLow diversity = narrow repetitive task pattern.">
        <span class="stat-label">Tools used <span class="tip-icon">?</span></span>
        <span class="stat-val">\${noActivity ? '—' : eff.toolBreakdown.length}</span>
      </div>
    </div>
    <div class="eff-panel">
      <h4>Time Saved Today</h4>
      <div class="stat-row" data-tip="Estimated typing time saved at 60 words/min.\nBased on today's total output tokens from Claude.">
        <span class="stat-label">Typing <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${todayOut > 0 ? '+'+Math.round(todayOut*0.75/60)+'m' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Estimated reading time saved at 250 words/min.\nBased on today's total input tokens processed by Claude.">
        <span class="stat-label">Reading <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${todayIn > 0 ? '+'+Math.round(todayIn*0.75/250)+'m' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="~1.5 min saved per tool action (context-switch cost if done manually).\nRunning a Grep, Edit, or Bash by hand costs focus time.">
        <span class="stat-label">Tool actions <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${totalCalls > 0 ? '+'+Math.round(totalCalls*1.5)+'m' : '—'}</span>
      </div>
      <div class="total-row" data-tip="Sum of all estimated time savings today.\nMath: 250wpm reading, 60wpm typing, 1.5m per tool context-switch.">
        <span style="font-weight:600;color:var(--green)">Total</span>
        <span style="font-weight:700;color:var(--green)">\${timeSaved}</span>
      </div>
    </div>
  \`;

  // File Heatmap
  if (eff.fileStats && Object.keys(eff.fileStats).length > 0) {
    const sortedFiles = Object.entries(eff.fileStats)
      .sort((a,b) => b[1] - a[1])
      .slice(0, 10);
    
    const heatmapHtml = sortedFiles.map(([path, count]) => {
      const opacity = Math.min(1, 0.2 + (count / sortedFiles[0][1] * 0.8));
      return \`<div class="stat-row" style="background:rgba(0,122,204,\${opacity/5});padding:3px 8px;border-radius:3px;border-bottom:none">
        <span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;font-size:10px">\${path}</span>
        <span style="font-weight:700;color:var(--accent);min-width:28px;text-align:right">\${count}x</span>
      </div>\`;
    }).join('');

    el.innerHTML += \`
      <div class="eff-panel" style="grid-column:1/-1;margin-top:10px">
        <h4>File Access Heatmap (Top 10)</h4>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:4px">
          \${heatmapHtml}
        </div>
      </div>
    \`;
  }
}

function renderHeatmap(days) {
  const el = document.getElementById('day-chart');
  if (!days || days.length === 0) {
    el.innerHTML = '<p class="empty">No daily data yet</p>';
    return;
  }

  // Build a lookup of date → DaySummary
  const byDate = {};
  days.forEach(d => { byDate[d.date] = d; });
  const maxCost = Math.max(...days.map(d => d.estimatedCostUsd), 0.001);

  // Build 52-week grid ending today
  const today = new Date();
  today.setHours(0,0,0,0);
  // Start from Sunday 52 weeks ago
  const startDate = new Date(today);
  startDate.setDate(startDate.getDate() - (52 * 7) + 1);
  // Back up to previous Sunday
  startDate.setDate(startDate.getDate() - startDate.getDay());

  // Month labels: collect first column where month changes
  const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const monthLabels = []; // {col, label}
  let prevMonth = -1;

  const cols = [];
  let d = new Date(startDate);
  let col = 0;
  while (d <= today) {
    const cells = [];
    for (let row = 0; row < 7; row++) {
      if (d > today) { cells.push(null); d.setDate(d.getDate()+1); continue; }
      const dateStr = d.toISOString().slice(0,10);
      const dayData = byDate[dateStr];
      const cost = dayData ? dayData.estimatedCostUsd : 0;
      const level = cost === 0 ? 0
        : cost < maxCost * 0.25 ? 1
        : cost < maxCost * 0.5  ? 2
        : cost < maxCost * 0.75 ? 3 : 4;
      const isToday = dateStr === today.toISOString().slice(0,10);
      cells.push({ dateStr, level, isToday, dayData });
      if (d.getMonth() !== prevMonth && row === 0) {
        monthLabels.push({ col, label: monthNames[d.getMonth()] });
        prevMonth = d.getMonth();
      }
      d.setDate(d.getDate()+1);
    }
    cols.push(cells);
    col++;
  }

  // Render month labels row
  const cellSize = 12, gap = 3, dayLabelW = 24;
  const colPx = cellSize + gap;
  const monthHtml = \`<div style="display:flex;margin-left:\${dayLabelW}px;margin-bottom:2px;position:relative;height:14px">\${
    monthLabels.map(m => \`<span style="position:absolute;left:\${m.col*colPx}px;font-size:9px;color:var(--muted)">\${m.label}</span>\`).join('')
  }</div>\`;

  // Day labels (Mon, Wed, Fri)
  const dayLabels = ['','Mon','','Wed','','Fri',''];
  const dayLabelHtml = \`<div class="heatmap-day-labels">\${
    dayLabels.map(l => \`<div class="heatmap-day-label">\${l}</div>\`).join('')
  }</div>\`;

  // Columns of cells
  const colsHtml = cols.map(cells =>
    \`<div class="heatmap-col">\${cells.map(c => {
      if (!c) return \`<div class="heatmap-cell l0"></div>\`;
      const outline = c.isToday ? 'outline:1px solid var(--accent);outline-offset:-1px;' : '';
      const tip = c.dayData
        ? \`data-tip="\${c.dateStr}&#10;\${c.dayData.sessions} sessions · \${c.dayData.turns} turns&#10;Est. \$\${c.dayData.estimatedCostUsd.toFixed(2)}"\`
        : \`data-tip="\${c.dateStr}&#10;No activity"\`;
      return \`<div class="heatmap-cell l\${c.level}" style="\${outline}" \${tip}></div>\`;
    }).join('')}</div>\`
  ).join('');

  // Legend
  const legendHtml = \`<div class="heatmap-legend">
    <span class="heatmap-legend-label">Less</span>
    \${[0,1,2,3,4].map(l => \`<div class="heatmap-cell l\${l}" style="flex-shrink:0"></div>\`).join('')}
    <span class="heatmap-legend-label">More</span>
  </div>\`;

  el.innerHTML = \`<div class="heatmap-wrap">
    \${monthHtml}
    <div style="display:flex">
      \${dayLabelHtml}
      <div class="heatmap-grid">\${colsHtml}</div>
    </div>
    \${legendHtml}
  </div>\`;
}

function card(label, value, sub, tip='') {
  return \`<div class="card"\${tip ? \` data-tip="\${tip.replace(/"/g,'&quot;')}"\` : ''}>
    <div class="card-label">\${label}\${tip ? ' <span class="tip-icon">?</span>' : ''}</div>
    <div class="card-value">\${value}</div>
    <div class="card-sub">\${sub}</div>
  </div>\`;
}
function cardWithBar(label, value, sub, pct, color, tip='') {
  return \`<div class="card"\${tip ? \` data-tip="\${tip.replace(/"/g,'&quot;')}"\` : ''}>
    <div class="card-label">\${label}\${tip ? ' <span class="tip-icon">?</span>' : ''}</div>
    <div class="card-value" style="color:\${color}">\${value}</div>
    <div style="margin:3px 0;height:3px;background:var(--border);border-radius:2px">
      <div style="height:100%;width:\${pct}%;background:\${color};border-radius:2px;transition:width .3s"></div>
    </div>
    <div class="card-sub">\${sub}</div>
  </div>\`;
}
</script>
</body>
</html>`;
  }
}
