import * as vscode from 'vscode';
import { SessionSummary, DaySummary, ActivityRecord, EfficiencyStats } from './types';

export class UsageDashboardPanel implements vscode.Disposable {
  static currentPanel: UsageDashboardPanel | undefined;

  private readonly panel: vscode.WebviewPanel;
  private disposables: vscode.Disposable[] = [];
  
  private lastActivity: ActivityRecord[] = [];
  private lastProject?: string;
  private lastEfficiency?: EfficiencyStats;

  static show(): UsageDashboardPanel {
    if (UsageDashboardPanel.currentPanel) {
      UsageDashboardPanel.currentPanel.panel.reveal();
      return UsageDashboardPanel.currentPanel;
    }
    const panel = vscode.window.createWebviewPanel(
      'claudeUsageDashboard',
      'Claude Usage',
      vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    UsageDashboardPanel.currentPanel = new UsageDashboardPanel(panel);
    return UsageDashboardPanel.currentPanel;
  }

  private constructor(panel: vscode.WebviewPanel) {
    this.panel = panel;
    this.panel.onDidDispose(() => this.dispose(), null, this.disposables);
    this.panel.webview.onDidReceiveMessage(message => {
      if (message.command === 'installHooks') {
        vscode.commands.executeCommand('claudeUsage.installHooks');
      } else if (message.command === 'refresh' || message.command === 'ready') {
        vscode.commands.executeCommand('claudeUsage.refresh');
      }
    }, undefined, this.disposables);
    this.panel.webview.html = this.skeleton();
  }

  update(
    sessions: SessionSummary[], days: DaySummary[], activity: ActivityRecord[],
    hooksActive: boolean, currentProject?: string,
    liveMetrics?: { contextPct: number | null; fiveHourPct: number | null; sevenDayPct: number | null; fiveHourResetsAt: Date | null },
    efficiency?: EfficiencyStats
  ): void {
    this.lastActivity = activity;
    this.lastProject = currentProject;
    this.lastEfficiency = efficiency;
    this.panel.webview.postMessage({ type: 'update', sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency });
  }

  private async exportSessionToMarkdown(): Promise<void> {
    if (this.lastActivity.length === 0) {
      vscode.window.showWarningMessage('No activity data to export.');
      return;
    }

    let md = `# Claude Session Export: ${this.lastProject || 'Untracked Project'}\n`;
    md += `*Generated by Claude Usage Monitor*\n\n`;
    
    if (this.lastEfficiency) {
      md += `## Efficiency Stats\n`;
      md += `- **Total Tool Calls:** ${this.lastEfficiency.totalToolCalls}\n`;
      md += `- **Bash Error Rate:** ${Math.round(this.lastEfficiency.bashErrorRate * 100)}%\n`;
      if (this.lastEfficiency.sessionCostUsd) {
        md += `- **Estimated Cost (Today):** $${this.lastEfficiency.sessionCostUsd.toFixed(2)}\n`;
      }
      md += `\n`;
    }

    md += `## Tool Usage Sequence\n\n`;
    md += `| Timestamp | Event | Tool | Summary | Duration |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    // Process records - group Pre/Post if possible or just list them
    for (const r of this.lastActivity) {
      const time = new Date(r.ts).toLocaleTimeString();
      const dur = r.durationMs ? `${(r.durationMs / 1000).toFixed(1)}s` : '-';
      const event = r.event === 'PreToolUse' ? '▶ Start' : r.event === 'PostToolUse' ? '✓ End' : r.event;
      md += `| ${time} | ${event} | \`${r.tool || '-'}\` | ${r.summary || '-'} | ${dur} |\n`;
    }

    md += `\n\n--- \n*Use this log to reconcile your Anthropic billing or to document AI-driven architectural changes.*`;

    const doc = await vscode.workspace.openTextDocument({
      content: md,
      language: 'markdown'
    });
    await vscode.window.showTextDocument(doc);
  }

  reveal(): void {
    this.panel.reveal();
  }

  dispose(): void {
    UsageDashboardPanel.currentPanel = undefined;
    this.panel.dispose();
    this.disposables.forEach(d => d.dispose());
  }

  private skeleton(): string {
    return /* html */`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Claude Usage</title>
<style>
  :root {
    --bg: var(--vscode-editor-background);
    --fg: var(--vscode-editor-foreground);
    --border: var(--vscode-panel-border, #2a2a2a);
    --card-bg: var(--vscode-sideBar-background, #1a1a1a);
    --accent: var(--vscode-focusBorder, #007acc);
    --accent-hover: var(--vscode-textLink-activeForeground, #005a9e);
    --muted: var(--vscode-descriptionForeground, #666);
    --green: #4ec9b0;
    --yellow: #dcdcaa;
    --red: #f44747;
    --glass-bg: rgba(255,255,255,0.02);
    --glass-border: rgba(255,255,255,0.05);
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: var(--vscode-font-family); font-size: 11px; color: var(--fg); background: var(--bg); padding: 12px 14px; max-width: 1200px; margin: 0 auto; }

  h2 { font-size: 13px; font-weight: 700; display: flex; align-items: center; gap: 8px; }
  h3 { font-size: 10px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: .8px; }
  h4 { font-size: 10px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: .6px; margin-bottom: 8px; padding-bottom: 5px; border-bottom: 1px solid var(--glass-border); }

  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid var(--border); }
  button { background: var(--card-bg); color: var(--fg); border: 1px solid var(--border); padding: 3px 9px; border-radius: 4px; cursor: pointer; font-size: 11px; transition: border-color .15s; }
  button:hover { border-color: var(--accent); }
  button.primary { background: var(--accent); color: #fff; border-color: var(--accent); }

  /* Cards */
  .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 8px; margin-bottom: 12px; animation: fadeIn .3s ease; }
  .card { background: var(--card-bg); border: 1px solid var(--glass-border); border-radius: 5px; padding: 10px 12px; cursor: default; }
  .card-label { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: .4px; margin-bottom: 3px; }
  .card-value { font-size: 18px; font-weight: 700; line-height: 1.1; }
  .card-sub { font-size: 10px; color: var(--muted); margin-top: 3px; }

  /* Collapsible section */
  .section { margin-bottom: 8px; border: 1px solid var(--glass-border); border-radius: 5px; overflow: hidden; }
  .section-header { display: flex; align-items: center; justify-content: space-between; padding: 7px 10px; cursor: pointer; user-select: none; background: var(--glass-bg); }
  .section-header:hover { background: rgba(255,255,255,0.03); }
  .section-header h3 { margin: 0; }
  .section-header .toggle { font-size: 9px; color: var(--muted); transition: transform .2s; }
  .section-header.collapsed .toggle { transform: rotate(-90deg); }
  .section-body { padding: 10px 12px; }
  .section-body.hidden { display: none; }

  /* Tables */
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { text-align: left; padding: 4px 8px; color: var(--muted); font-weight: 600; border-bottom: 1px solid var(--border); white-space: nowrap; }
  td { padding: 4px 8px; border-bottom: 1px solid var(--glass-border); vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  .model-tag { font-size: 10px; padding: 1px 5px; border-radius: 8px; background: rgba(0,122,204,.15); border: 1px solid rgba(0,122,204,.25); color: var(--accent); }
  .cost { color: var(--yellow); }

  /* Grade */
  .grade-badge { width: 28px; height: 28px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 900; color: #fff; }
  .grade-s { background: linear-gradient(135deg,#ffd700,#ff8c00); }
  .grade-a { background: linear-gradient(135deg,#4ec9b0,#007acc); }
  .grade-b { background: linear-gradient(135deg,#007acc,#c586c0); }
  .grade-c { background: linear-gradient(135deg,#888,#555); }
  .grade-f { background: linear-gradient(135deg,#f44747,#b22222); }

  /* Notice */
  .notice { display: flex; align-items: center; justify-content: space-between; gap: 10px; padding: 7px 10px; background: rgba(244,71,71,.08); border-left: 3px solid var(--red); border-radius: 0 4px 4px 0; font-size: 11px; margin-bottom: 8px; }
  .btn-install { background: var(--green); color: #000; border: none; padding: 3px 9px; border-radius: 4px; font-weight: 600; cursor: pointer; font-size: 11px; white-space: nowrap; }

  /* Efficiency */
  .eff-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }
  .tool-bar-row { display: flex; align-items: center; gap: 6px; margin-bottom: 5px; }
  .tool-bar-label { width: 64px; flex-shrink: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .tool-bar-track { flex: 1; height: 6px; background: rgba(0,0,0,0.25); border-radius: 3px; overflow: hidden; }
  .tool-bar-fill { height: 100%; border-radius: 3px; transition: width .5s cubic-bezier(.1,.8,.2,1); }
  .tool-bar-count { width: 24px; text-align: right; color: var(--muted); }
  .tool-bar-dur { width: 34px; text-align: right; color: var(--muted); }
  .stat-row { display: flex; justify-content: space-between; align-items: center; padding: 4px 0; border-bottom: 1px solid var(--glass-border); }
  .stat-row:last-child { border-bottom: none; }
  .stat-label { display: flex; align-items: center; gap: 4px; }
  .stat-val { font-weight: 700; }
  .stat-val.good { color: var(--green); }
  .stat-val.warn { color: var(--yellow); }
  .stat-val.bad  { color: var(--red); }
  .alert-pill { display: inline-flex; align-items: center; gap: 5px; padding: 3px 7px; border-radius: 3px; font-size: 10px; font-weight: 600; margin-bottom: 5px; }
  .alert-pill.runaway { background: rgba(244,71,71,.15); color: var(--red); border: 1px solid rgba(244,71,71,.3); }
  .alert-pill.budget  { background: rgba(220,220,170,.15); color: var(--yellow); border: 1px solid rgba(220,220,170,.3); }
  .total-row { display: flex; justify-content: space-between; align-items: center; padding: 6px 8px; border-radius: 4px; background: rgba(78,201,176,.08); border: 1px solid rgba(78,201,176,.2); margin-top: 8px; }

  /* Filter */
  .filter-row { display: flex; align-items: center; gap: 6px; }
  .filter-row select { background: var(--bg); color: var(--fg); border: 1px solid var(--border); border-radius: 4px; padding: 2px 6px; font-size: 11px; cursor: pointer; outline: none; }
  .project-badge { font-size: 10px; padding: 1px 6px; border-radius: 8px; background: var(--accent); color: #fff; font-weight: 600; }

  /* Day trend chart */
  .chart-wrap { position: relative; }
  .chart-tooltip { position: absolute; background: var(--card-bg); border: 1px solid var(--border); border-radius: 4px; padding: 4px 8px; font-size: 10px; pointer-events: none; display: none; white-space: nowrap; z-index: 10; }
  svg.trend text { font-family: var(--vscode-font-family); }

  /* Hover tooltip */
  .tip { position: fixed; background: var(--card-bg); border: 1px solid var(--border); border-radius: 4px; padding: 6px 9px; font-size: 10px; line-height: 1.5; pointer-events: none; display: none; white-space: pre-line; z-index: 100; max-width: 240px; color: var(--fg); box-shadow: 0 4px 12px rgba(0,0,0,.4); }
  [data-tip] { cursor: help; }
  .tip-icon { font-size: 9px; color: var(--muted); opacity: .6; }

  .empty { color: var(--muted); font-size: 11px; padding: 20px; text-align: center; }
  @keyframes fadeIn { from { opacity:0 } to { opacity:1 } }
</style>
</head>
<body>
<div class="header">
  <div style="display:flex;align-items:center;gap:12px">
    <h2>⚡ Claude Usage</h2>
    <div id="score-container" style="display:flex;align-items:center;gap:8px;border-left:1px solid var(--border);padding-left:12px"></div>
  </div>
  <button class="primary" onclick="refresh()">↻</button>
</div>

<div id="cards" class="cards"></div>
<div id="hooks-notice"></div>

<div class="section">
  <div class="section-header" onclick="toggleSection(this)">
    <h3>Efficiency</h3>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body">
    <div id="efficiency-section" class="eff-grid"></div>
  </div>
</div>

<div class="section">
  <div class="section-header collapsed" onclick="toggleSection(this)">
    <div class="filter-row">
      <h3>Sessions</h3>
      <select id="project-filter" onchange="applyFilter()" onclick="event.stopPropagation()">
        <option value="">All projects</option>
      </select>
      <span id="active-badge" style="display:none" class="project-badge"></span>
    </div>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body hidden">
    <div id="sessions-table"></div>
  </div>
</div>

<div class="section">
  <div class="section-header" onclick="toggleSection(this)">
    <h3>Daily Trend</h3>
    <span class="toggle">▼</span>
  </div>
  <div class="section-body">
    <div class="chart-wrap">
      <div id="chart-tooltip" class="chart-tooltip"></div>
      <div id="day-chart"></div>
    </div>
  </div>
</div>

<div id="tip" class="tip"></div>

<script>
const vscode = acquireVsCodeApi();
function refresh() { vscode.postMessage({ command: 'refresh' }); }

// Signal the extension that the webview is ready — request initial data push
vscode.postMessage({ command: 'ready' });

function toggleSection(header) {
  header.classList.toggle('collapsed');
  const body = header.nextElementSibling;
  if (body) body.classList.toggle('hidden');
}

// Global hover tooltip — any element with data-tip shows an explanation
const _tip = document.getElementById('tip');
document.addEventListener('mouseover', e => {
  const el = e.target.closest('[data-tip]');
  if (!el) return;
  _tip.textContent = el.dataset.tip;
  _tip.style.display = 'block';
});
document.addEventListener('mousemove', e => {
  if (_tip.style.display === 'none') return;
  const x = e.clientX + 14, y = e.clientY + 12;
  const maxX = window.innerWidth  - _tip.offsetWidth  - 8;
  const maxY = window.innerHeight - _tip.offsetHeight - 8;
  _tip.style.left = Math.min(x, maxX) + 'px';
  _tip.style.top  = Math.min(y, maxY) + 'px';
});
document.addEventListener('mouseout', e => {
  if (!e.target.closest('[data-tip]')) return;
  _tip.style.display = 'none';
});

let _allSessions = [];
let _days = [];
let _currentProject = '';

function fmtK(n) {
  if (n >= 1e6) return (n/1e6).toFixed(1)+'M';
  if (n >= 1e3) return (n/1e3).toFixed(0)+'K';
  return n+'';
}
function fmtCost(c) { return c < 0.01 ? '<$0.01' : '$'+c.toFixed(2); }
function relTime(ts) {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff/60000);
  if (m < 1) return 'just now';
  if (m < 60) return m+'m ago';
  const h = Math.floor(m/60);
  if (h < 24) return h+'h ago';
  return Math.floor(h/24)+'d ago';
}

// Readable session label: "project / MM-DD HH:mm" — slug shown on hover
function sessionLabel(s) {
  const d = new Date(s.firstTs);
  const mm = String(d.getMonth()+1).padStart(2,'0');
  const dd = String(d.getDate()).padStart(2,'0');
  const hh = String(d.getHours()).padStart(2,'0');
  const mi = String(d.getMinutes()).padStart(2,'0');
  return \`\${s.project} / \${mm}-\${dd} \${hh}:\${mi}\`;
}

function applyFilter() {
  const sel = document.getElementById('project-filter').value;
  renderSessions(sel ? _allSessions.filter(s => s.project === sel) : _allSessions);
}

function renderSessions(sessions) {
  document.getElementById('sessions-table').innerHTML = sessions.length === 0
    ? '<p class="empty">No sessions match</p>'
    : \`<table>
      <tr><th>Session</th><th>Model</th><th>Turns</th><th>Tok/turn</th><th>In</th><th>Out</th><th>Cache%</th><th>Ctx%</th><th>Cost</th><th>Last</th></tr>
      \${sessions.slice(0,30).map(s => {
        const totalIn = s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens;
        const cacheHit = totalIn > 0 ? Math.round(s.cacheReadTokens/totalIn*100) : 0;
        const ctxColor = s.contextPct >= 80 ? 'var(--red)' : s.contextPct >= 60 ? 'var(--yellow)' : 'inherit';
        return \`<tr title="\${s.slug}">
          <td>\${sessionLabel(s)}</td>
          <td><span class="model-tag">\${s.model.replace('claude-','').replace('-4-6','4.6').replace('-4-5','4.5')}</span></td>
          <td>\${s.turns}</td>
          <td>\${fmtK(s.tokensPerTurn??0)}</td>
          <td>\${fmtK(totalIn)}</td>
          <td>\${fmtK(s.outputTokens)}</td>
          <td>\${cacheHit}%</td>
          <td style="color:\${ctxColor}">\${s.contextPct}%</td>
          <td class="cost">\${fmtCost(s.estimatedCostUsd)}</td>
          <td>\${relTime(s.lastTs)}</td>
        </tr>\`;
      }).join('')}
    </table>\`;
}

window.addEventListener('message', e => {
  const msg = e.data;
  if (msg.type !== 'update') return;
  const { sessions, days, activity, hooksActive, currentProject, liveMetrics, efficiency } = msg;

  _allSessions = sessions;
  _days = days;
  _currentProject = currentProject ?? '';

  // Score display
  const scoreContainer = document.getElementById('score-container');
  if (efficiency && efficiency.dailyScore !== undefined) {
    const g = (efficiency.grade || 'C').toLowerCase();
    scoreContainer.innerHTML = \`
      <div class="grade-badge grade-\${g}" data-tip="Prompt Engineer Score: \${efficiency.dailyScore}/100\nBased on bash error rate, context efficiency, and tool diversity.\nS=elite  A=great  B=good  C=average  F=needs work">\${efficiency.grade}</div>
      <span style="color:var(--muted)">\${efficiency.dailyScore}/100</span>
    \`;
  } else {
    scoreContainer.innerHTML = '';
  }

  // Populate project filter dropdown, preserve current selection
  const filterEl = document.getElementById('project-filter');
  const prevSel = filterEl.value;
  const projects = [...new Set(sessions.map(s => s.project))].sort();
  filterEl.innerHTML = '<option value="">All projects</option>'
    + projects.map(p => \`<option value="\${p}"\${p===prevSel?' selected':''}>\${p}</option>\`).join('');

  // Show active project badge and auto-select current workspace on first load
  const badge = document.getElementById('active-badge');
  if (currentProject) {
    badge.style.display = 'inline';
    badge.textContent = currentProject;
    // Auto-select current workspace only if filter hasn't been manually changed
    if (!prevSel && projects.includes(currentProject)) {
      filterEl.value = currentProject;
    }
  } else {
    badge.style.display = 'none';
  }

  // Summary cards — always across ALL sessions for today (not filtered)
  const today = new Date().toISOString().slice(0,10);
  const todaySessions = sessions.filter(s => s.lastTs.slice(0,10) === today);
  const todayIn   = todaySessions.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const todayOut  = todaySessions.reduce((a,s) => a+s.outputTokens, 0);
  const todayCost = todaySessions.reduce((a,s) => a+s.estimatedCostUsd, 0);
  const latest    = sessions[0] ?? null;

  // Prefer live context % from statusLine if available
  const ctxPct = liveMetrics?.contextPct ?? latest?.contextPct ?? 0;
  const ctxColor = ctxPct >= 80 ? 'var(--red)' : ctxPct >= 60 ? 'var(--yellow)' : 'var(--green)';

  // Cache efficiency across today
  const todayTotalInput = todaySessions.reduce((a,s) => a+s.inputTokens+s.cacheReadTokens+s.cacheCreateTokens, 0);
  const todayCacheRead  = todaySessions.reduce((a,s) => a+s.cacheReadTokens, 0);
  const cacheHitPct = todayTotalInput > 0 ? Math.round(todayCacheRead / todayTotalInput * 100) : 0;

  const fiveHourPct  = liveMetrics?.fiveHourPct  ?? null;
  const sevenDayPct  = liveMetrics?.sevenDayPct  ?? null;
  const fiveHourReset = liveMetrics?.fiveHourResetsAt
    ? 'resets '+new Date(liveMetrics.fiveHourResetsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
    : 'subscription limit';

  document.getElementById('cards').innerHTML = [
    card('Today In',  fmtK(todayIn),  todaySessions.length+' sessions · '+fmtCost(todayCost)+' est.',
      'Tokens sent TO Claude today across all sessions.\nIncludes input + cache reads + cache writes.\nHigh input = lots of context re-sent each turn.'),
    card('Today Out', fmtK(todayOut), 'cache hit '+cacheHitPct+'%',
      'Tokens generated BY Claude today.\nCache hit % = share of input served from cache (saves cost).\nHigher cache hit = more efficient prompting.'),
    cardWithBar('Context Window', Math.round(ctxPct)+'%', latest ? sessionLabel(latest)+' · '+fmtK(latest.tokensPerTurn??0)+'/turn' : '—', ctxPct, ctxColor,
      'How full the active session context is (max 200K tokens).\n>60% = approaching limit, consider /compact.\n>80% = risk of truncation or degraded responses.'),
    fiveHourPct !== null
      ? cardWithBar('5-Hour Limit', Math.round(fiveHourPct)+'%', fiveHourReset, fiveHourPct, fiveHourPct>=80?'var(--red)':fiveHourPct>=60?'var(--yellow)':'var(--green)',
          'Rolling 5-hour usage cap for Claude subscriptions.\nResets automatically. If this hits 100% Claude stops responding until reset.')
      : card('Total Sessions', sessions.length+'', sessions.reduce((a,s)=>a+s.turns,0)+' turns total',
          'Total JSONL session files found in ~/.claude/projects/.\nEach session = one Claude conversation thread.'),
    sevenDayPct !== null
      ? cardWithBar('7-Day Limit', Math.round(sevenDayPct)+'%', 'subscription limit', sevenDayPct, sevenDayPct>=80?'var(--red)':sevenDayPct>=60?'var(--yellow)':'var(--green)',
          '7-day rolling usage cap for Claude subscriptions.\nResets weekly. High usage here may indicate runaway agents or very long sessions.')
      : card('Total Sessions', sessions.length+'', sessions.reduce((a,s)=>a+s.turns,0)+' turns total',
          'Total JSONL session files found in ~/.claude/projects/.\nEach session = one Claude conversation thread.'),
  ].filter((v,i,a) => a.indexOf(v)===i).join(''); // dedup if both rate limit cards are null

  // Activity feed
  // Hooks notice
  const noticeEl = document.getElementById('hooks-notice');
  if (!hooksActive) {
    noticeEl.style.display = 'block';
    noticeEl.innerHTML = \`
      <div class="notice">
        <div><strong>Live activity requires hooks.</strong> Your ~/.claude/settings.json needs to be updated.</div>
        <button class="btn-install" onclick="vscode.postMessage({command: 'installHooks'})">1-Click Auto Install</button>
      </div>
    \`;
  } else {
    noticeEl.style.display = 'none';
  }

  // Efficiency section
  renderEfficiency(efficiency, todayIn, todayOut);

  // Sessions table — apply current filter
  applyFilter();

  // Daily trend chart
  renderDayChart(days);
});

const TOOL_COLORS = {
  Bash: '#4ec9b0', Edit: '#569cd6', Write: '#9cdcfe', Read: '#dcdcaa',
  Grep: '#c586c0', Glob: '#ce9178', WebFetch: '#4fc1ff', Agent: '#f44747',
};

function renderEfficiency(eff, todayIn, todayOut) {
  const el = document.getElementById('efficiency-section');
  if (!eff) {
    el.innerHTML = '<p class="empty" style="grid-column:1/-1">No efficiency data — hooks required</p>';
    return;
  }
  const noActivity = eff.totalToolCalls === 0;

  // Tool breakdown
  const maxCalls = eff.toolBreakdown[0]?.calls ?? 1;
  const toolRows = noActivity
    ? '<p class="empty" style="padding:16px 0">No tool calls yet this session</p>'
    : eff.toolBreakdown.slice(0, 8).map(s => {
        const color = TOOL_COLORS[s.tool] ?? '#888';
        const pct = Math.round(s.calls / maxCalls * 100);
        const dur = eff.avgToolDurationMs[s.tool]
          ? (eff.avgToolDurationMs[s.tool] >= 1000
              ? (eff.avgToolDurationMs[s.tool]/1000).toFixed(1)+'s'
              : eff.avgToolDurationMs[s.tool]+'ms')
          : '';
        return \`<div class="tool-bar-row">
          <span class="tool-bar-label">\${s.tool}</span>
          <div class="tool-bar-track"><div class="tool-bar-fill" style="width:\${pct}%;background:\${color}"></div></div>
          <span class="tool-bar-count">\${s.calls}</span>
          <span class="tool-bar-dur">\${dur}</span>
        </div>\`;
      }).join('');

  // Stats panel
  const totalCalls = eff.totalToolCalls;
  const errPct = noActivity ? null : Math.round(eff.bashErrorRate * 100);
  const errClass = errPct === null ? '' : errPct >= 30 ? 'bad' : errPct >= 15 ? 'warn' : 'good';

  const ctxEff = eff.contextEfficiency;
  const ctxEffPct = (ctxEff !== null && !noActivity) ? Math.round(ctxEff * 100) : null;
  const ctxEffClass = ctxEffPct === null ? '' : ctxEffPct >= 15 ? 'good' : ctxEffPct >= 5 ? 'warn' : 'bad';

  const readWritePct = eff.toolBreakdown
    .filter(s => ['Read','Write','Edit'].includes(s.tool))
    .reduce((a,s) => a + s.calls, 0);
  const actionRatio = totalCalls > 0 ? Math.round(readWritePct / totalCalls * 100) : null;

  const alertsHtml = [
    eff.isRunaway  ? \`<div class="alert-pill runaway">⚠ High Bash error rate — possible runaway agent</div>\` : '',
    eff.budgetExceeded ? \`<div class="alert-pill budget">💰 Session cost exceeded $2.00 threshold</div>\` : '',
  ].join('');

  const timeSaved = (() => {
    const m = ((todayIn||0)*0.75/250) + ((todayOut||0)*0.75/60) + (totalCalls*1.5);
    if (m < 1) return '—';
    const h = Math.floor(m/60);
    return h > 0 ? h+'h '+Math.floor(m%60)+'m' : Math.floor(m)+'m';
  })();

  el.innerHTML = \`
    <div class="eff-panel">
      <h4>Tool Distribution — \${totalCalls} calls</h4>
      \${toolRows}
    </div>
    <div class="eff-panel">
      <h4>Session Health</h4>
      \${alertsHtml}
      <div class="stat-row" data-tip="% of Bash tool calls that returned non-zero exit code.\n>30% = Claude thrashing on shell commands.\n>15% = worth reviewing the session.">
        <span class="stat-label">Bash error rate <span class="tip-icon">?</span></span>
        <span class="stat-val \${errClass}">\${errPct !== null ? errPct+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Output tokens ÷ input tokens.\nHigher = Claude producing more per token consumed.\nLow (5%) = mostly reading, little writing.\nGood (15%+) = solid generation-to-consumption ratio.">
        <span class="stat-label">Context efficiency <span class="tip-icon">?</span></span>
        <span class="stat-val \${ctxEffClass}">\${ctxEffPct !== null ? ctxEffPct+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="% of tool calls spent on file operations (Read/Write/Edit).\nHigh = file-editing-heavy session.\nLow = more search/bash/web activity.">
        <span class="stat-label">File op ratio <span class="tip-icon">?</span></span>
        <span class="stat-val">\${actionRatio !== null ? actionRatio+'%' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Number of distinct tools used in this session.\nHigher diversity = Claude using the full toolkit.\nLow diversity = narrow repetitive task pattern.">
        <span class="stat-label">Tools used <span class="tip-icon">?</span></span>
        <span class="stat-val">\${noActivity ? '—' : eff.toolBreakdown.length}</span>
      </div>
    </div>
    <div class="eff-panel">
      <h4>Time Saved Today</h4>
      <div class="stat-row" data-tip="Estimated typing time saved at 60 words/min.\nBased on today's total output tokens from Claude.">
        <span class="stat-label">Typing <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${todayOut > 0 ? '+'+Math.round(todayOut*0.75/60)+'m' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="Estimated reading time saved at 250 words/min.\nBased on today's total input tokens processed by Claude.">
        <span class="stat-label">Reading <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${todayIn > 0 ? '+'+Math.round(todayIn*0.75/250)+'m' : '—'}</span>
      </div>
      <div class="stat-row" data-tip="~1.5 min saved per tool action (context-switch cost if done manually).\nRunning a Grep, Edit, or Bash by hand costs focus time.">
        <span class="stat-label">Tool actions <span class="tip-icon">?</span></span>
        <span class="stat-val good">\${totalCalls > 0 ? '+'+Math.round(totalCalls*1.5)+'m' : '—'}</span>
      </div>
      <div class="total-row" data-tip="Sum of all estimated time savings today.\nMath: 250wpm reading, 60wpm typing, 1.5m per tool context-switch.">
        <span style="font-weight:600;color:var(--green)">Total</span>
        <span style="font-weight:700;color:var(--green)">\${timeSaved}</span>
      </div>
    </div>
  \`;

  // File Heatmap
  if (eff.fileStats && Object.keys(eff.fileStats).length > 0) {
    const sortedFiles = Object.entries(eff.fileStats)
      .sort((a,b) => b[1] - a[1])
      .slice(0, 10);
    
    const heatmapHtml = sortedFiles.map(([path, count]) => {
      const opacity = Math.min(1, 0.2 + (count / sortedFiles[0][1] * 0.8));
      return \`<div class="stat-row" style="background:rgba(0,122,204,\${opacity/5});padding:3px 8px;border-radius:3px;border-bottom:none">
        <span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;font-size:10px">\${path}</span>
        <span style="font-weight:700;color:var(--accent);min-width:28px;text-align:right">\${count}x</span>
      </div>\`;
    }).join('');

    el.innerHTML += \`
      <div class="eff-panel" style="grid-column:1/-1;margin-top:10px">
        <h4>File Access Heatmap (Top 10)</h4>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:4px">
          \${heatmapHtml}
        </div>
      </div>
    \`;
  }
}

function renderDayChart(days) {
  const el = document.getElementById('day-chart');
  if (!days || days.length === 0) {
    el.innerHTML = '<p class="empty">No daily data yet</p>';
    return;
  }
  const today = new Date().toISOString().slice(0, 10);
  const data = days.slice(0, 14).reverse(); // oldest → newest left-to-right
  const maxCost = Math.max(...data.map(d => d.estimatedCostUsd), 0.001);
  const W = 560, H = 72, pad = 3;
  const barW = Math.floor((W - pad * (data.length + 1)) / data.length);
  const bars = data.map((d, i) => {
    const x = pad + i * (barW + pad);
    const h = Math.max(3, Math.round(d.estimatedCostUsd / maxCost * H));
    const y = H - h;
    const isToday = d.date === today;
    const fill = isToday ? 'var(--accent)' : 'var(--muted)';
    const lbl = d.date.slice(5); // MM-DD
    return \`<rect x="\${x}" y="\${y}" width="\${barW}" height="\${h}" rx="2" fill="\${fill}" opacity="\${isToday ? 1 : 0.45}"
      data-date="\${d.date}" data-sessions="\${d.sessions}" data-turns="\${d.turns}" data-cost="\${d.estimatedCostUsd.toFixed(3)}"
      style="cursor:pointer"/>
    <text x="\${x + barW/2}" y="\${H + 13}" text-anchor="middle" font-size="8" fill="var(--muted)">\${lbl}</text>\`;
  }).join('');
  el.innerHTML = \`<svg class="trend" viewBox="0 0 \${W} \${H + 18}" width="100%" style="display:block"
    onmousemove="dayChartHover(event)" onmouseleave="dayChartLeave()">
    \${bars}
  </svg>\`;
}

function dayChartHover(e) {
  const rect = e.target.closest('rect');
  if (!rect || !rect.dataset.date) return;
  const tip = document.getElementById('chart-tooltip');
  tip.style.display = 'block';
  tip.innerHTML = \`<strong>\${rect.dataset.date}</strong><br/>\${rect.dataset.sessions} sessions · \${rect.dataset.turns} turns<br/>Est. $\${rect.dataset.cost}\`;
  const bounds = e.currentTarget.getBoundingClientRect();
  const tipLeft = e.clientX - bounds.left + 12;
  const tipTop  = e.clientY - bounds.top  - 40;
  tip.style.left = tipLeft + 'px';
  tip.style.top  = tipTop  + 'px';
}

function dayChartLeave() {
  const tip = document.getElementById('chart-tooltip');
  if (tip) tip.style.display = 'none';
}

function card(label, value, sub, tip='') {
  return \`<div class="card"\${tip ? \` data-tip="\${tip.replace(/"/g,'&quot;')}"\` : ''}>
    <div class="card-label">\${label}\${tip ? ' <span class="tip-icon">?</span>' : ''}</div>
    <div class="card-value">\${value}</div>
    <div class="card-sub">\${sub}</div>
  </div>\`;
}
function cardWithBar(label, value, sub, pct, color, tip='') {
  return \`<div class="card"\${tip ? \` data-tip="\${tip.replace(/"/g,'&quot;')}"\` : ''}>
    <div class="card-label">\${label}\${tip ? ' <span class="tip-icon">?</span>' : ''}</div>
    <div class="card-value" style="color:\${color}">\${value}</div>
    <div style="margin:3px 0;height:3px;background:var(--border);border-radius:2px">
      <div style="height:100%;width:\${pct}%;background:\${color};border-radius:2px;transition:width .3s"></div>
    </div>
    <div class="card-sub">\${sub}</div>
  </div>\`;
}
</script>
</body>
</html>`;
  }
}
